/**
 * Aspekt-aligned Vergleichsmatrix je Themenfeld.
 *
 * Autor: Claude Code (manuell, KEIN LLM/API), neutral aus den BTW-2025-Programm-
 * texten in partei_themenfeld_position.position abgeleitet. Die Aspekt-Zeilen sind
 * die SUMME dessen, was die Parteien im jeweiligen Feld selbst thematisieren.
 *
 * Zelle = kurze Position der Partei zu DIESEM Aspekt, oder null = im Programm nicht
 * adressiert ("n/a"). Phase 2 (n/a aus Reden/Q&A/Abstimmungen füllen) ist NICHT
 * Teil dieser Datei.
 */
export interface VergleichAspekt {
  label: string;
  /** key = kanonischer Parteiname (CDU/CSU, AfD, SPD, GRÜNE, LINKE); Wert null = n/a */
  zellen: Record<string, string | null>;
}
export interface FeldMatrix {
  aspekte: VergleichAspekt[];
}

export const VERGLEICH_MATRIX: Record<string, FeldMatrix> = {
  "Arbeit und Beschäftigung": {
    aspekte: [
      { label: "Mindestlohn", zellen: {
        "CDU/CSU": "Kommission unabhängig, keine politische Festsetzung",
        "AfD": null,
        "SPD": "Auf 15 € anheben",
        "GRÜNE": "15 €, auch für unter 18-Jährige",
        "LINKE": "Rund 15 €, 2026: 16 €" } },
      { label: "Tarifbindung", zellen: {
        "CDU/CSU": "Stärken, Betriebsratsgründung erleichtern",
        "AfD": null,
        "SPD": "Ausweiten",
        "GRÜNE": "Tariftreuegesetz für öffentliche Aufträge",
        "LINKE": "Bundestariftreuegesetz, Allgemeinverbindlichkeit" } },
      { label: "Befristung & prekäre Arbeit", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Sachgrundlose Befristung abschaffen",
        "GRÜNE": "Gegen Scheinselbstständigkeit/Werkverträge",
        "LINKE": "Leiharbeit und Befristung abschaffen" } },
      { label: "Betriebliche Mitbestimmung", zellen: {
        "CDU/CSU": "Erleichtern, digitale Formate",
        "AfD": null,
        "SPD": "Ausbauen (KI, Personalplanung)",
        "GRÜNE": "Bei Klima, Qualifizierung, Gleichstellung",
        "LINKE": "Erzwingbare Veto-Rechte" } },
      { label: "Arbeitslosengeld", zellen: {
        "CDU/CSU": null,
        "AfD": "Erst nach 3 Beitragsjahren, zunächst 6 Monate",
        "SPD": "Stärken, Qualifizierung nicht anrechnen",
        "GRÜNE": null,
        "LINKE": "68 % des letzten Lohns" } },
      { label: "Bürgergeld / Grundsicherung", zellen: {
        "CDU/CSU": "Mitwirkung schärfer, Vermögensprüfung ab Tag 1",
        "AfD": "Gemeinnützige Arbeit nach 6 Monaten, strenger für Ausländer",
        "SPD": "Aktive Vermittlung, Mitwirkungspflichten bleiben",
        "GRÜNE": null,
        "LINKE": "Sanktionsfreie Mindestsicherung" } },
      { label: "Fachkräfte", zellen: {
        "CDU/CSU": "Anerkennung beschleunigen, „Work-and-Stay-Agentur“",
        "AfD": "Erst heimische Potenziale; bestreitet Mangel",
        "SPD": "Anerkennung erleichtern",
        "GRÜNE": "Anerkennung, Integration Geflüchteter",
        "LINKE": null } },
      { label: "Arbeitszeit", zellen: {
        "CDU/CSU": "Arbeitszeitgesetz reformieren, Homeoffice absichern",
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Digitale Erfassung ohne Verlängerung",
        "LINKE": "4-Tage-Woche bei vollem Lohnausgleich" } },
      { label: "Weiterbildung & Ausbildung", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Recht auf Weiterbildung",
        "GRÜNE": "Ausbildungsgarantie",
        "LINKE": "Ausbildungsumlage, Mindestvergütung" } },
      { label: "Langzeitarbeitslose / sozialer Arbeitsmarkt", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Sozialen Arbeitsmarkt entfristen",
        "GRÜNE": null,
        "LINKE": "Staatliche Beschäftigungsprogramme" } },
      { label: "Minijobs", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "In Sozialversicherung einbeziehen",
        "GRÜNE": null,
        "LINKE": "Sozialversicherungspflicht ab dem 1. Euro" } },
      { label: "Entgeltgleichheit", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "EU-Entgelttransparenz umsetzen",
        "LINKE": null } },
      { label: "Ukraine-Flüchtlinge im Bürgergeld", zellen: {
        "CDU/CSU": null,
        "AfD": "Aus dem Bürgergeld ausgliedern",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
    ],
  },
  "Außenpolitik und internationale Beziehungen": {
    aspekte: [
      { label: "Ukraine-Unterstützung", zellen: {
        "CDU/CSU": "Diplomatie, Finanzen, Waffen",
        "AfD": "Neutral, keine Waffen; Krieg beenden",
        "SPD": "Militärisch/finanziell, aber keine Kriegspartei",
        "GRÜNE": "Unterstützen, Sanktionen ausweiten",
        "LINKE": "Waffenlieferungen stoppen, Verhandlungen" } },
      { label: "Russland-Sanktionen", zellen: {
        "CDU/CSU": "Gezielt erweitern",
        "AfD": "Aufheben, Nord Stream reaktivieren",
        "SPD": "Mittragen",
        "GRÜNE": "Ausweiten, russische Vermögen nutzen",
        "LINKE": "Nur gegen den Machtapparat" } },
      { label: "NATO", zellen: {
        "CDU/CSU": "Unverzichtbar",
        "AfD": "Zentral, aber keine US-Mittelstreckenraketen",
        "SPD": "Zentraler Pfeiler",
        "GRÜNE": "Sicherheitsrahmen",
        "LINKE": "Ablehnen (Relikt des Kalten Krieges)" } },
      { label: "China", zellen: {
        "CDU/CSU": "Systemkonkurrenz, Abhängigkeiten senken",
        "AfD": "Ausbau, Schutz vor Technologieabfluss",
        "SPD": "Partner, Wettbewerber, Systemrivale",
        "GRÜNE": "De-Risking",
        "LINKE": null } },
      { label: "Israel & Nahost", zellen: {
        "CDU/CSU": "Sicherheit Israels als Staatsräson",
        "AfD": null,
        "SPD": "Existenzrecht + Zweistaatenlösung, Waffenstillstand",
        "GRÜNE": "Existenzrecht + Zweistaatenlösung (1967)",
        "LINKE": "Waffenstillstand, Palästina anerkennen, keine Waffen an Israel" } },
      { label: "EU-Außenpolitik & Souveränität", zellen: {
        "CDU/CSU": "Stärker koordinieren, EU-Verteidigungsunion",
        "AfD": "Strategische Autonomie, eigenes Militärbündnis",
        "SPD": "Europäische Verteidigungsunion",
        "GRÜNE": "Europäische Souveränität stärken",
        "LINKE": "EU zur Friedensunion umbauen" } },
      { label: "Abrüstung & Atomwaffen", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "New START, „No first use“",
        "GRÜNE": "Atomwaffenfreie Welt",
        "LINKE": "Nukleare Teilhabe beenden, US-Atomwaffen abziehen" } },
      { label: "UN & Multilateralismus", zellen: {
        "CDU/CSU": null,
        "AfD": "Ständiger Sicherheitsratssitz, Feindstaatenklausel streichen",
        "SPD": "UN und G20 stärken",
        "GRÜNE": "UN-Reform",
        "LINKE": "UN stärken, gerechte Weltwirtschaftsordnung" } },
      { label: "Globaler Süden", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Partnerschaft auf Augenhöhe, koloniales Erbe aufarbeiten",
        "GRÜNE": "Vertrauen und Transparenz",
        "LINKE": "Koloniale Ausbeutung beenden" } },
      { label: "UN-Migrationspakt / WHO-Vertrag", zellen: {
        "CDU/CSU": null,
        "AfD": "Kündigen / ablehnen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
    ],
  },
  "Bildung und Erziehung": {
    aspekte: [
      { label: "Frühkindliche Bildung / Kita", zellen: {
        "CDU/CSU": "Sprachförderung vor der Schule, Betreuungsausbau",
        "AfD": "Vorschulklassen gegen Sprachdefizite",
        "SPD": "Verbindliche Förderung ab dem 4. Lebensjahr",
        "GRÜNE": "Bundesweite Qualitätsstandards, vergütete Ausbildung",
        "LINKE": "Kitaqualitätsgesetz, bessere Betreuungsschlüssel" } },
      { label: "Schulsystem", zellen: {
        "CDU/CSU": "Vergleichbare Abiturstandards, Ganztag",
        "AfD": "Mehrgliedriges System, Leistungsorientierung",
        "SPD": "Ganztagsanspruch ab 2026 umsetzen",
        "GRÜNE": "Modernisierung, multiprofessionelle Teams",
        "LINKE": "Eine inklusive Gemeinschaftsschule statt gegliedert" } },
      { label: "Inklusion / Förderschulen", zellen: {
        "CDU/CSU": null,
        "AfD": "Förderschulen als Regelfall, Inklusion „mit Augenmaß“",
        "SPD": null,
        "GRÜNE": "Inklusion stärken",
        "LINKE": "Inklusiv, Förderschulen abschaffen" } },
      { label: "Digitalisierung der Schulen", zellen: {
        "CDU/CSU": "Ausbau, MINT fördern",
        "AfD": "Erste 4 Schuljahre weitgehend digitalfrei",
        "SPD": "Digitalpakt Schule fortsetzen",
        "GRÜNE": "Digitale Ausstattung im Investitionsprogramm",
        "LINKE": null } },
      { label: "Berufliche Bildung", zellen: {
        "CDU/CSU": "Gleichwertig zur akademischen, duale Ausbildung",
        "AfD": "Duale Ausbildung aufwerten",
        "SPD": "Höhere Mindestausbildungsvergütung",
        "GRÜNE": "Inklusive Ausbildungsgarantie",
        "LINKE": "Solidarische Ausbildungsumlage" } },
      { label: "BAföG / Studienfinanzierung", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Reform, Anpassung an Lebenskosten, Rückkehr zum Vollzuschuss",
        "GRÜNE": "Existenzsichernd, elternunabhängiger",
        "LINKE": "Eltern-/altersunabhängiger Vollzuschuss" } },
      { label: "Hochschulen", zellen: {
        "CDU/CSU": "Stabile Finanzierung, weniger Bürokratie",
        "AfD": "Mehr Autonomie, Diplom/Magister zurück",
        "SPD": "Bessere Lehre, planbare Karrieren",
        "GRÜNE": "Weniger Befristung, „Zukunfts-Campus“",
        "LINKE": "Mehr Dauerstellen, Grundfinanzierung" } },
      { label: "Bund-Länder-Zuständigkeit", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Mehr Kooperation Bund/Länder",
        "LINKE": "Kooperationsverbot aufheben, 100-Mrd.-Sondervermögen" } },
      { label: "Sprache / Migration in Schulen", zellen: {
        "CDU/CSU": "Verbindliche Sprachförderung",
        "AfD": "Pflicht-Deutschunterricht, Islam-Einfluss zurückdrängen",
        "SPD": "Bildungssystem für Einwanderungsgesellschaft",
        "GRÜNE": "Diskriminierungssensibles Lernen",
        "LINKE": null } },
      { label: "Demokratiebildung / Wahlalter", zellen: {
        "CDU/CSU": null,
        "AfD": "Politische Neutralität, gegen „Indoktrination“",
        "SPD": "Demokratiebildung, Wahlalter 16",
        "GRÜNE": null,
        "LINKE": null } },
    ],
  },
  "Energie": {
    aspekte: [
      { label: "Kernenergie", zellen: {
        "CDU/CSU": "Wiedereinstieg prüfen (SMR, Fusion)",
        "AfD": "Reaktoren reaktivieren, Wiedereinstieg",
        "SPD": null,
        "GRÜNE": "Ausstieg vollenden",
        "LINKE": "Atomausstieg ins Grundgesetz" } },
      { label: "Kohle", zellen: {
        "CDU/CSU": "Ausstieg nur mit Gas-Ersatz",
        "AfD": "Braunkohleausstieg stoppen, Ausbau",
        "SPD": null,
        "GRÜNE": "Ausstieg 2030",
        "LINKE": "Ausstieg bis 2030" } },
      { label: "Erneuerbare Energien", zellen: {
        "CDU/CSU": "Ausbau plus Netzausbau",
        "AfD": "Ohne Subvention/Vorrang, Wind-/PV-Ausbau ablehnen",
        "SPD": "Zentrale Säule, Wind/Solar + Speicher",
        "GRÜNE": "Strom bis 2035 zu 100 % erneuerbar",
        "LINKE": "Ausbau, Solarpflicht für Neubau" } },
      { label: "Strompreise / Netzentgelte", zellen: {
        "CDU/CSU": "Stromsteuer und Netzentgelte senken",
        "AfD": "Energiesteuern abschaffen",
        "SPD": "Netzentgelte auf 3 ct/kWh deckeln",
        "GRÜNE": "Stromsteuer senken, Netzentgelte reformieren",
        "LINKE": "Merit-Order abschaffen, soziale Tarife" } },
      { label: "Fossiles Gas", zellen: {
        "CDU/CSU": "Neue Gaskraftwerke als Ersatz",
        "AfD": "Nord Stream reparieren, Gas/Heizöl",
        "SPD": null,
        "GRÜNE": "Bis spätestens 2045 beenden",
        "LINKE": "Ausstieg bis 2035" } },
      { label: "Heizen / Wärme", zellen: {
        "CDU/CSU": "Heizungsgesetz abschaffen, technologieoffen",
        "AfD": "Gas und Heizöl bevorzugen",
        "SPD": "Kommunale Wärmeplanung",
        "GRÜNE": "Wärmewende, Fernwärme dekarbonisieren",
        "LINKE": "Sozial gestaffelte Förderung für Heizungstausch" } },
      { label: "Wasserstoff", zellen: {
        "CDU/CSU": "Infrastruktur und Partnerschaften",
        "AfD": "Als nicht wettbewerbsfähig verworfen",
        "SPD": "Grüner Wasserstoff für Industrie",
        "GRÜNE": "Wasserstoffkernnetz aufbauen",
        "LINKE": "Nur grüner Wasserstoff, nur Industrie" } },
      { label: "CO₂-Preis / Klimageld", zellen: {
        "CDU/CSU": "CO₂-Preis mit Klimabonus",
        "AfD": "CO₂-Abgabe abschaffen",
        "SPD": null,
        "GRÜNE": "EEG-Umlage weg, Klimageld",
        "LINKE": "Klimageld, Übergewinne abschöpfen" } },
      { label: "Öffentliches Eigentum an Energie", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Energy Sharing fördern",
        "LINKE": "Netze rekommunalisieren, öffentliche Hand" } },
      { label: "Strom-/Gassperren", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Verbieten" } },
    ],
  },
  "Entwicklungspolitik": {
    aspekte: [
      { label: "Grundausrichtung", zellen: {
        "CDU/CSU": "Mit Sicherheit, Migration und Geopolitik verknüpfen",
        "AfD": "An deutschen Sicherheits-/Wirtschaftsinteressen",
        "SPD": "Strategische Partnerschaften, feministisch",
        "GRÜNE": "Feministisch, inklusiv, dekolonial",
        "LINKE": "Soziale Gerechtigkeit, Selbstbestimmung" } },
      { label: "Mittelhöhe / Finanzierung", zellen: {
        "CDU/CSU": null,
        "AfD": "Kürzen, strikt an Bedingungen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "0,7 % der Wirtschaftsleistung" } },
      { label: "Konditionierung der Hilfe", zellen: {
        "CDU/CSU": "An Rückführungs-/Sicherheitsziele",
        "AfD": "An Rücknahme Ausreisepflichtiger koppeln",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Von Militär/Profit trennen" } },
      { label: "Humanitäre Hilfe / Struktur", zellen: {
        "CDU/CSU": "Mit Entwicklungszusammenarbeit zusammenführen",
        "AfD": "Sachleistungen statt Geld",
        "SPD": "Soziale Sicherungssysteme stärken",
        "GRÜNE": "Enger mit humanitärer Hilfe verzahnen",
        "LINKE": "Klimafinanzierung zusätzlich" } },
      { label: "Fokus Frauen / Gleichstellung", zellen: {
        "CDU/CSU": "Frauen und Mädchen, Familienplanung",
        "AfD": null,
        "SPD": "Gleiche Rechte unabhängig vom Geschlecht",
        "GRÜNE": "Geschlechtergerechtigkeit verankern",
        "LINKE": "Schutz von Frauen, Kindern, LSBTIQ+" } },
      { label: "Handel / Lieferketten", zellen: {
        "CDU/CSU": "Private Investitionen fördern",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Faire Abkommen statt Freihandel, Lieferkettengesetz stärken" } },
      { label: "Schuldenerlass / globale Steuer", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Schuldenschnitt, globale Milliardärsteuer" } },
      { label: "Patente / Medikamente", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Patente auf lebenswichtige Medikamente überwinden" } },
    ],
  },
  "Europapolitik und Europäische Union": {
    aspekte: [
      { label: "Grundhaltung zur EU", zellen: {
        "CDU/CSU": "EU als Erfolgsgeschichte, Interessen vertreten",
        "AfD": "Austritt aus dem Euro, nationale Währung",
        "SPD": "Vertiefte, handlungsfähigere EU",
        "GRÜNE": "Handlungsfähige EU, mehr Sicherheitskooperation",
        "LINKE": "Sozial-demokratischer Umbau, weg vom Neoliberalismus" } },
      { label: "EU-Erweiterung", zellen: {
        "CDU/CSU": null,
        "AfD": "Osterweiterung ablehnen",
        "SPD": "Westbalkan, Ukraine, Moldau (bei Kriterien)",
        "GRÜNE": null,
        "LINKE": "Solidarisch, mit Standards" } },
      { label: "Entscheidungsregeln", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Einstimmigkeit durch Mehrheit ersetzen",
        "GRÜNE": null,
        "LINKE": "EP-Initiativrecht, EU-Volksbegehren" } },
      { label: "EU-Finanzen / Eigenmittel", zellen: {
        "CDU/CSU": null,
        "AfD": "Kein EU-Besteuerungsrecht, keine EU-Schulden",
        "SPD": "Banken- und Kapitalmarktunion",
        "GRÜNE": null,
        "LINKE": "Investitionen statt Schuldenregeln" } },
      { label: "Binnenmarkt / Handel", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Binnenmarkt ausbauen",
        "GRÜNE": "Handel mit verbindlichen Öko-/Sozialstandards",
        "LINKE": null } },
      { label: "Militarisierung der EU", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Über 2 % für Verteidigung",
        "LINKE": "Ablehnen, Frontex zur Rettungsmission" } },
      { label: "Euro / Währung", zellen: {
        "CDU/CSU": null,
        "AfD": "Transferunion ablehnen, Staatsgold heimholen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Rechtsstaatlichkeit / Menschenrechte", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Sanktionen bei Verstößen, EU-Beitritt zur EMRK",
        "GRÜNE": null,
        "LINKE": "Gegen Sanktionen (z. B. Kuba)" } },
    ],
  },
  "Gesellschaftspolitik, soziale Gruppen": {
    aspekte: [
      { label: "Familienförderung", zellen: {
        "CDU/CSU": "Kinderfreibetrag anheben, Kindergeld automatisch",
        "AfD": "Betreuungsgehalt, Familiensplitting",
        "SPD": "Kindergrundsicherung, Elterngeld 18 Monate",
        "GRÜNE": "Kindergrundsicherung (automatisiert)",
        "LINKE": "Kindergrundsicherung, gebührenfreie Betreuung" } },
      { label: "Ehegattensplitting", zellen: {
        "CDU/CSU": "Beibehalten",
        "AfD": "Zu Familiensplitting umbauen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Abschaffen" } },
      { label: "Kinderrechte ins Grundgesetz", zellen: {
        "CDU/CSU": null,
        "AfD": "Ablehnen",
        "SPD": "Verankern",
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Selbstbestimmungsgesetz (trans/inter)", zellen: {
        "CDU/CSU": "Für Minderjährige ablehnen",
        "AfD": "Ablehnen",
        "SPD": null,
        "GRÜNE": "Elternschaft für trans/inter anerkennen",
        "LINKE": "Verbessern" } },
      { label: "Queere Gleichstellung", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Schutz ins GG, queere Familien gleichstellen",
        "GRÜNE": "Diskriminierungsschutz ins GG, Regenbogenfamilien",
        "LINKE": "Schutz ins GG, queere Infrastruktur" } },
      { label: "Parität / Frauenrechte", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Parität bis 2030, Paritätsgesetz",
        "GRÜNE": "AGG-Reform, Schutz vor Gewalt",
        "LINKE": "Individualbesteuerung, reproduktive Rechte" } },
      { label: "Menschen mit Behinderung", zellen: {
        "CDU/CSU": "Teilhabe, Förderschulen stärken",
        "AfD": "Förderschulen erhalten",
        "SPD": "Inklusion, Barrierefreiheit",
        "GRÜNE": "UN-Behindertenrechtskonvention umsetzen",
        "LINKE": "Barrierefreiheit, Förderschulen abschaffen" } },
      { label: "Islam / Religionsgemeinschaften", zellen: {
        "CDU/CSU": "Gemeindeleben (mit FDGO), Auslandsfinanzierung stoppen",
        "AfD": "Gegen organisierten Islam",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Staatsleistungen an Kirchen abschaffen" } },
      { label: "Alleinerziehende", zellen: {
        "CDU/CSU": "Entlastungsbetrag erhöhen",
        "AfD": null,
        "SPD": "Steuerlich entlasten",
        "GRÜNE": "Steuergutschrift",
        "LINKE": null } },
      { label: "Antisemitismus / jüdisches Leben", zellen: {
        "CDU/CSU": "Nationale Strategie",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Verantwortungsgemeinschaft (jenseits Ehe)", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Einführen",
        "LINKE": null } },
      { label: "Teilhabe von Migrant:innen", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Offenes Einwanderungsrecht, Partizipationsgesetz" } },
    ],
  },
  "Gesundheit": {
    aspekte: [
      { label: "Krankenversicherung", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Bürgerversicherung",
        "GRÜNE": "Bürgerversicherung",
        "LINKE": "Solidarische Vollversicherung, Privatvers. in GKV" } },
      { label: "Pflegefinanzierung", zellen: {
        "CDU/CSU": "Finanzierungsmix, private Vorsorge",
        "AfD": "Häusliche Pflege höher honorieren",
        "SPD": "Eigenanteil auf 1.000 €/Monat deckeln",
        "GRÜNE": "Pflegebürgerversicherung",
        "LINKE": "Eigenanteile abschaffen, Pflegevollversicherung" } },
      { label: "Pflegepersonal", zellen: {
        "CDU/CSU": "Beruf attraktiver, Auslandsanwerbung",
        "AfD": null,
        "SPD": "Bessere Löhne und Personalausstattung",
        "GRÜNE": "Bessere Personalschlüssel",
        "LINKE": "100.000 zusätzliche Kräfte" } },
      { label: "Krankenhausfinanzierung (Fallpauschalen)", zellen: {
        "CDU/CSU": null,
        "AfD": "DRG-Fallpauschalen abschaffen",
        "SPD": null,
        "GRÜNE": "Gemeinwohl statt Finanzinvestoren",
        "LINKE": "Ohne Fallpauschalen, öffentlich" } },
      { label: "Digitalisierung (ePA)", zellen: {
        "CDU/CSU": "ePA, KI",
        "AfD": "Telematik-Infrastruktur ablehnen",
        "SPD": "ePA, Telemedizin",
        "GRÜNE": "ePA, Bürokratieabbau",
        "LINKE": null } },
      { label: "Arzneimittelversorgung", zellen: {
        "CDU/CSU": "Lieferketten sichern",
        "AfD": "Rx-Versandhandel verbieten, Produktion zurückholen",
        "SPD": "Produktion in DE/EU",
        "GRÜNE": null,
        "LINKE": "Pharma öffentlich kontrollieren" } },
      { label: "Impfen", zellen: {
        "CDU/CSU": null,
        "AfD": "Keine Impfpflicht, STIKO neutraler",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "WHO-/EU-Einfluss", zellen: {
        "CDU/CSU": null,
        "AfD": "Ablehnen, nationale Steuerung",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Organspende", zellen: {
        "CDU/CSU": null,
        "AfD": "Nur mit Zustimmung (keine Widerspruchslösung)",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Cannabis / Drogen", zellen: {
        "CDU/CSU": null,
        "AfD": "Verbieten",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Legalisieren, Drugchecking" } },
      { label: "Psychische Gesundheit", zellen: {
        "CDU/CSU": "Versorgung für Kinder/Jugendliche",
        "AfD": null,
        "SPD": "Prävention stärken",
        "GRÜNE": "Stärken",
        "LINKE": "Psychotherapie ausbauen" } },
      { label: "Versorgung ländlich / Notfall", zellen: {
        "CDU/CSU": "Notfallversorgung, Haus-/Kinderärzte",
        "AfD": null,
        "SPD": "Strukturschwache Regionen",
        "GRÜNE": "Notfallreform, Gesundheitskioske",
        "LINKE": "Kommunale Versorgungszentren" } },
    ],
  },
  "Innere Sicherheit": {
    aspekte: [
      { label: "Videoüberwachung / Gesichtserkennung", zellen: {
        "CDU/CSU": "An Kriminalitätsschwerpunkten ausbauen",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Biometrische Überwachung ablehnen" } },
      { label: "Strafen verschärfen", zellen: {
        "CDU/CSU": "Härter (Messer, Stalking, häusliche Gewalt)",
        "AfD": "Härter, Strafvollzug auch in Drittstaaten",
        "SPD": "Gewalt gegen Frauen/Kinder härter ahnden",
        "GRÜNE": null,
        "LINKE": "Sonderstrafrecht abschaffen" } },
      { label: "Strafmündigkeit / Jugendstrafrecht", zellen: {
        "CDU/CSU": "Heranwachsende ins allgemeine Strafrecht",
        "AfD": "Strafmündigkeit auf 12 senken",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Ausländische Straftäter", zellen: {
        "CDU/CSU": "Konsequent verfolgen",
        "AfD": "Ausweisen, Präventivhaft für Gefährder",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Polizei (Ausstattung/Ausrichtung)", zellen: {
        "CDU/CSU": "Schutz der Einsatzkräfte",
        "AfD": "Bessere Besoldung, Ausrüstung, Befugnisse",
        "SPD": "Personell stärken, Bundespolizeigesetz",
        "GRÜNE": "Modern, grundrechtskonform",
        "LINKE": "Deeskalierend, ohne Militärausrüstung" } },
      { label: "Überwachungsbefugnisse / Vorratsdaten", zellen: {
        "CDU/CSU": "IP-Speicherung, mehr Befugnisse",
        "AfD": "Ablehnen",
        "SPD": "Automatisierte Datenanalyse",
        "GRÜNE": "Keine anlasslose Massenüberwachung",
        "LINKE": "Vorratsdaten/Staatstrojaner ablehnen" } },
      { label: "Organisierte / Clankriminalität", zellen: {
        "CDU/CSU": "Umfassendes Maßnahmenpaket",
        "AfD": "Vermögenseinzug, Abschiebung",
        "SPD": "Gegen OK und Cybercrime",
        "GRÜNE": "Zentrum OK, Finanzpolizei",
        "LINKE": null } },
      { label: "Extremismusbekämpfung", zellen: {
        "CDU/CSU": "Extremistische Moscheen schließen, Entwaffnung",
        "AfD": "Gegen Links- und Islamismus, Verbote",
        "SPD": "Rechtsextremismus/Islamismus, Finanzquellen",
        "GRÜNE": "Prävention, Gefährder überwachen",
        "LINKE": "Beobachtungsstelle statt Verfassungsschutz" } },
      { label: "Verfassungsschutz", zellen: {
        "CDU/CSU": null,
        "AfD": "Grundlegend reformieren",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Durch unabhängige Stelle ersetzen, V-Leute beenden" } },
      { label: "Kennzeichnungspflicht Polizei", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Anonymisierte Kennzeichnung",
        "LINKE": "Individuelle Kennzeichnungspflicht" } },
      { label: "Racial Profiling", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Verbieten" } },
      { label: "Verschleierung (Burka/Kopftuch)", zellen: {
        "CDU/CSU": null,
        "AfD": "Im öffentlichen Dienst/Schulen verbieten",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Waffenrecht", zellen: {
        "CDU/CSU": null,
        "AfD": "Legalwaffenbesitzer entlasten",
        "SPD": null,
        "GRÜNE": "Verschärfen",
        "LINKE": null } },
    ],
  },
  "Kultur": {
    aspekte: [
      { label: "Kultur als Staatsziel (GG)", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Verankern",
        "GRÜNE": "Verankern",
        "LINKE": "Zur Pflichtaufgabe machen" } },
      { label: "Erinnerungskultur", zellen: {
        "CDU/CSU": "Zwei Diktaturen plus Kolonialismus",
        "AfD": "Gegen „Umdeutung“, ganze Geschichte würdigen",
        "SPD": "NS, SED, Kolonialismus",
        "GRÜNE": "NS/SED/Kolonial, für Einwanderungsgesellschaft öffnen",
        "LINKE": null } },
      { label: "Gendersprache", zellen: {
        "CDU/CSU": "Keine verpflichtende",
        "AfD": "In öffentlichen Einrichtungen verbieten",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Soziale Lage der Künstler:innen", zellen: {
        "CDU/CSU": "Sponsoring/Mäzenatentum",
        "AfD": "Umsatzsteuerbefreiung bis Einkommensgrenze",
        "SPD": "Künstlersozialkasse ausbauen",
        "GRÜNE": "Künstlersozialversicherung, Honoraruntergrenzen",
        "LINKE": "Basishonorare, KSK öffnen" } },
      { label: "Restitution / koloniales Erbe", zellen: {
        "CDU/CSU": null,
        "AfD": "Keine pauschale Rückgabe",
        "SPD": null,
        "GRÜNE": "Provenienzforschung, Rückführung",
        "LINKE": "Rückgabe unrechtmäßig erworbener Güter" } },
      { label: "Deutsche Sprache / Leitkultur", zellen: {
        "CDU/CSU": "Christliches Erbe, Sonntagsruhe schützen",
        "AfD": "Deutsch als Staatssprache ins GG, Leitkultur",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Clubs / Pop- und Subkultur", zellen: {
        "CDU/CSU": "Clubs als Kulturorte anerkennen",
        "AfD": "Brauchtum, lokale Vereine",
        "SPD": "Clubs, Games",
        "GRÜNE": "Clubs/Livestätten rechtlich schützen",
        "LINKE": null } },
      { label: "KI / Urheberrecht", zellen: {
        "CDU/CSU": "KI in der Kultur nutzen",
        "AfD": null,
        "SPD": "KI-Inhalte kennzeichnen, Urheberrechte",
        "GRÜNE": "KI-Auswirkungen prüfen",
        "LINKE": "KI-Training vergüten" } },
      { label: "Kulturhoheit: Bund vs. Länder", zellen: {
        "CDU/CSU": "Gemeinsam Bund/Länder/Kommunen",
        "AfD": "Länderhoheit stärken, Bund begrenzen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Kooperationsverbot beenden" } },
      { label: "Film- / Games-Förderung", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Filmförderung reformieren",
        "GRÜNE": "Games-Steuerförderung, kleine Verlage",
        "LINKE": "Filmförderung mit Diversitätsbeirat" } },
    ],
  },
  "Landwirtschaft und Ernährung": {
    aspekte: [
      { label: "EU-Agrarpolitik (GAP)", zellen: {
        "CDU/CSU": "Entbürokratisieren",
        "AfD": "Ablehnen",
        "SPD": "Agrarförderung reformieren",
        "GRÜNE": "Öffentliche Gelder für öffentliche Leistungen",
        "LINKE": null } },
      { label: "Pestizide / Pflanzenschutz", zellen: {
        "CDU/CSU": "Zulassungen beschleunigen",
        "AfD": "Bedarfsgerecht, weniger Bürokratie",
        "SPD": null,
        "GRÜNE": "Einsatz reduzieren",
        "LINKE": "Glyphosat verbieten, −50 % bis 2030" } },
      { label: "Tierhaltung & Tierwohl", zellen: {
        "CDU/CSU": "Tierwohlställe fördern, Kombihaltung erhalten",
        "AfD": "Artgerecht, regionale Schlachthöfe",
        "SPD": "Tierschutz honorieren",
        "GRÜNE": "Weidehaltung, Haltungskennzeichnung ausweiten",
        "LINKE": "Flächengebunden, Megaställe schließen" } },
      { label: "Tiertransporte", zellen: {
        "CDU/CSU": null,
        "AfD": "Auf 6 Stunden begrenzen",
        "SPD": null,
        "GRÜNE": "Auf 4 Stunden begrenzen",
        "LINKE": "Über 4 Stunden verbieten" } },
      { label: "Gentechnik / Züchtung", zellen: {
        "CDU/CSU": "Moderne Züchtung („Smart Breeding“)",
        "AfD": "Streng überwachen, Forschung (CRISPR)",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Gentechnikfrei" } },
      { label: "Ökolandbau", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "30 % bis 2030",
        "LINKE": "Ökologische Agrarwende" } },
      { label: "Bodenmarkt / Spekulation", zellen: {
        "CDU/CSU": "Gegen Ausverkauf an Investoren",
        "AfD": "Investoren erschweren",
        "SPD": null,
        "GRÜNE": "Share Deals verhindern",
        "LINKE": "Vor Spekulation schützen, Gemeineigentum" } },
      { label: "Lebensmittelpreise / -steuer", zellen: {
        "CDU/CSU": "Gegen Lenkungssteuern, Herkunftskennzeichnung",
        "AfD": "Keine Fleisch-/Zuckersteuer",
        "SPD": "Mehrwertsteuer 7 → 5 %",
        "GRÜNE": null,
        "LINKE": "MwSt auf Grundnahrungsmittel abschaffen" } },
      { label: "Erzeugerpreise / Marktmacht", zellen: {
        "CDU/CSU": null,
        "AfD": "Faire Erzeugerpreise, Direktvermarktung",
        "SPD": "Marktmacht des Handels begrenzen",
        "GRÜNE": "Regionale Wertschöpfung",
        "LINKE": "Mindesterzeugerpreise" } },
      { label: "Ernährungssicherung als Staatsziel", zellen: {
        "CDU/CSU": "Ins Grundgesetz",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Wolf / Jagd", zellen: {
        "CDU/CSU": "Bejagbar machen",
        "AfD": "Wildbestände regulieren",
        "SPD": null,
        "GRÜNE": "Abschuss in Ausnahmen (Herdenschutz)",
        "LINKE": null } },
      { label: "Werbeverbot / Verschwendung", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Lebensmittelverschwendung reduzieren",
        "LINKE": "Werbeverbot Ungesundes, Containern entkriminalisieren" } },
    ],
  },
  "Medien, Kommunikation und Informationstechnik": {
    aspekte: [
      { label: "Überwachungsbefugnisse", zellen: {
        "CDU/CSU": "IP-Speicherung, Gesichtserkennung, TKÜ",
        "AfD": "Stark einschränken",
        "SPD": null,
        "GRÜNE": "Keine Massenüberwachung",
        "LINKE": "Staatstrojaner/Chatkontrolle ablehnen" } },
      { label: "Öffentlich-rechtlicher Rundfunk", zellen: {
        "CDU/CSU": "Auf Kernauftrag, sparsam",
        "AfD": "Verschlanken, gebührenfreie Grundversorgung",
        "SPD": "Auftragsgerecht finanzieren",
        "GRÜNE": "Auskömmlich finanzieren",
        "LINKE": "Vielfalt stärken, Beitrag sozial befreien" } },
      { label: "Desinformation / Hassrede", zellen: {
        "CDU/CSU": "DSA umsetzen",
        "AfD": "Gegen „Zensur“/Faktenchecker, NetzDG/DSA abschaffen",
        "SPD": "Bekämpfen, Medienkompetenz",
        "GRÜNE": "Strategie, Strafbarkeit ausländischer Kampagnen",
        "LINKE": "Plattformen haften für Falschinfos" } },
      { label: "Datenschutz (DSGVO)", zellen: {
        "CDU/CSU": "Pragmatischer gestalten",
        "AfD": "DSGVO durch schlankes BDSG ersetzen",
        "SPD": null,
        "GRÜNE": "Aufsicht reformieren",
        "LINKE": null } },
      { label: "Plattformregulierung (DSA/DMA)", zellen: {
        "CDU/CSU": "DSA umsetzen",
        "AfD": "DSA abschaffen",
        "SPD": "Algorithmen offenlegen, DSA/DMA durchsetzen",
        "GRÜNE": "DSA/DMA umsetzen",
        "LINKE": "Monopole zerschlagen, personalisierte Werbung verbieten" } },
      { label: "Breitband- / Netzausbau", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Glasfaser/5G, offene Standards",
        "LINKE": "Recht auf Internet (≥100 Mbit/s), Preise deckeln" } },
      { label: "Cybersicherheit (BSI)", zellen: {
        "CDU/CSU": "BSI als zentrale Stelle ausbauen",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "KI-Inhalte / Urheberrecht", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "KI-Inhalte kennzeichnen, Training vergüten" } },
      { label: "Open Source / Open Data", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Bei öffentlich finanzierter Software" } },
      { label: "NGO-Finanzierung offenlegen", zellen: {
        "CDU/CSU": null,
        "AfD": "Fordern",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
    ],
  },
  "Migration und Aufenthaltsrecht": {
    aspekte: [
      { label: "Grundhaltung", zellen: {
        "CDU/CSU": "Migration strikt begrenzen und kontrollieren",
        "AfD": "Umkehr, Regeln wie vor 1990",
        "SPD": "Moderne Einwanderungsgesellschaft",
        "GRÜNE": "Menschenrechtsbasiert",
        "LINKE": "Solidarisch, gleiche Rechte für alle" } },
      { label: "Asylverfahren in Drittstaaten", zellen: {
        "CDU/CSU": "Auslagern",
        "AfD": "Außerhalb Deutschlands",
        "SPD": "Ablehnen",
        "GRÜNE": "Ablehnen",
        "LINKE": "Ablehnen" } },
      { label: "Grenzkontrollen", zellen: {
        "CDU/CSU": "Verlängern, moderne Technik",
        "AfD": "Bundespolizei für Grenzschutz stärken",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Familiennachzug (subsidiär)", zellen: {
        "CDU/CSU": "Aussetzen",
        "AfD": "Streichen",
        "SPD": "Bleibt möglich",
        "GRÜNE": "Erleichtern, kein Sprachnachweis vorab",
        "LINKE": null } },
      { label: "Sozialleistungen für Asylbewerber", zellen: {
        "CDU/CSU": "Sachleistungen, Bezahlkarte",
        "AfD": "Aufs Existenzminimum, Sachleistungen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Reguläre Geldleistungen statt Sachleistungen" } },
      { label: "Seenotrettung", zellen: {
        "CDU/CSU": "Aufnahmeprogramme beenden",
        "AfD": "Zivile Seenotrettung ablehnen",
        "SPD": "Staatliche Seenotrettung",
        "GRÜNE": "Gegen Pushbacks",
        "LINKE": "Sichere Einreisewege" } },
      { label: "Rückführungen / Abschiebungen", zellen: {
        "CDU/CSU": "Erhöhen (auch Afghanistan/Syrien)",
        "AfD": "Große Rückführungsoffensive",
        "SPD": "Human, freiwillig bevorzugt",
        "GRÜNE": "Nicht in Kriegs-/Krisengebiete",
        "LINKE": "Abschaffen" } },
      { label: "Fachkräfteeinwanderung", zellen: {
        "CDU/CSU": null,
        "AfD": "Nur wenn dem Standort dienlich",
        "SPD": "Erleichtern",
        "GRÜNE": "Anerkennung, Arbeitsmarktzugang",
        "LINKE": null } },
      { label: "Einbürgerung / Staatsangehörigkeit", zellen: {
        "CDU/CSU": "Erst nach Integration, kein Doppelpass",
        "AfD": "Frühestens nach 10 Jahren, kaum Mehrstaatigkeit",
        "SPD": null,
        "GRÜNE": "Modern, Mehrstaatigkeit akzeptieren",
        "LINKE": "Nach 5 Jahren" } },
      { label: "Legale Fluchtwege", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Sichere legale Wege",
        "GRÜNE": "Humanitäre Aufnahme / Resettlement",
        "LINKE": "Sichere legale Einreisewege" } },
      { label: "EU-Verteilung (GEAS)", zellen: {
        "CDU/CSU": "Zentrale EU-Verfahren",
        "AfD": null,
        "SPD": "Solidarische Verteilung",
        "GRÜNE": "Faire EU-Verteilung",
        "LINKE": null } },
      { label: "Wahlrecht / Klimaflucht", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Wahlrecht für Langansässige, Klimaflucht anerkennen" } },
    ],
  },
  "Politisches Leben, Parteien": {
    aspekte: [
      { label: "Wahlrecht / Bundestagsgröße", zellen: {
        "CDU/CSU": "Verkleinern, Direktmandat erhalten",
        "AfD": "Freie Listenwahl (Kumulieren/Streichen)",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Direkte Demokratie / Bürgerräte", zellen: {
        "CDU/CSU": null,
        "AfD": "Volksabstimmungen nach Schweizer Vorbild",
        "SPD": "Bürgerräte etablieren",
        "GRÜNE": "Bürgerräte und Volksinitiativen",
        "LINKE": "Volksentscheide auf Bundesebene" } },
      { label: "Wahlalter 16", zellen: {
        "CDU/CSU": null,
        "AfD": "Ablehnen",
        "SPD": "Ja",
        "GRÜNE": "Ja",
        "LINKE": "Ja" } },
      { label: "Lobbytransparenz / Parteispenden", zellen: {
        "CDU/CSU": "Finanzierung offenlegen",
        "AfD": "Lobbyismus kontrollieren",
        "SPD": null,
        "GRÜNE": "Spenden deckeln, Karenzzeiten",
        "LINKE": "Unternehmensspenden verbieten, legislative Fußspur" } },
      { label: "Parteistiftungs-Finanzierung", zellen: {
        "CDU/CSU": "Keine Mittel für Auslandsfinanzierte",
        "AfD": "Abschaffen/radikal begrenzen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Demokratieförderung", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Demokratiefördergesetz",
        "GRÜNE": "Demokratiefördergesetz",
        "LINKE": null } },
      { label: "Verfassungsschutz", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Durch unabhängige Stelle ersetzen" } },
      { label: "Umgang mit der AfD", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Verbotsverfahren prüfen lassen",
        "LINKE": null } },
      { label: "Bundespräsident-Direktwahl", zellen: {
        "CDU/CSU": null,
        "AfD": "Direkt vom Volk wählen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Amtszeitbegrenzung / Briefwahl", zellen: {
        "CDU/CSU": null,
        "AfD": "Amtszeiten begrenzen, Briefwahl einschränken",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Paritätsgesetz", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Einführen",
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Wahlrecht für Nicht-Staatsbürger", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Nach 5 Jahren Aufenthalt" } },
    ],
  },
  "Raumordnung, Bau- und Wohnungswesen": {
    aspekte: [
      { label: "Mietpreisbremse / Mietendeckel", zellen: {
        "CDU/CSU": "Bestehende Regeln beibehalten",
        "AfD": "Ablehnen",
        "SPD": "Unbefristet, Schlupflöcher schließen",
        "GRÜNE": "Verlängern/verschärfen, Mietenstopp",
        "LINKE": "Bundesweiter Mietendeckel" } },
      { label: "Sozialer Wohnungsbau", zellen: {
        "CDU/CSU": "Auf Geschosswohnungsbau konzentrieren",
        "AfD": "Durch Wohngeld ersetzen",
        "SPD": "Ausbauen, Wohngemeinnützigkeit",
        "GRÜNE": "Ausbauen, unbefristete Bindungen",
        "LINKE": "20 Mrd. €/Jahr" } },
      { label: "Baurecht / Deregulierung", zellen: {
        "CDU/CSU": "Entschlacken, „Gebäudetyp E“",
        "AfD": "Deregulieren, Gebäudeenergiegesetz abschaffen",
        "SPD": "Baustandards vereinfachen",
        "GRÜNE": "Vereinfachen, digitalisieren",
        "LINKE": null } },
      { label: "Wohneigentum fördern", zellen: {
        "CDU/CSU": "Sonderabschreibung, Steueranreize",
        "AfD": "Grunderwerbsteuer abschaffen, Kaufoptionen",
        "SPD": "„Jung kauft Alt“",
        "GRÜNE": "Zinsgünstige Kredite für junge Familien",
        "LINKE": null } },
      { label: "Grundsteuer-Umlage auf Mieter", zellen: {
        "CDU/CSU": null,
        "AfD": "Grundsteuer abschaffen",
        "SPD": "Einschränken",
        "GRÜNE": "Beenden",
        "LINKE": null } },
      { label: "Eigenbedarfskündigung", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Auf Kernfamilie begrenzen",
        "GRÜNE": "Besser schützen",
        "LINKE": "Auf Verwandte 1. Grades begrenzen" } },
      { label: "Vergesellschaftung großer Vermieter", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Konzerne > 3.000 Wohnungen vergesellschaften" } },
      { label: "Leerstand", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Zweckentfremdung unterbinden",
        "GRÜNE": null,
        "LINKE": "Leerstandsabgabe" } },
      { label: "Obdachlosigkeit", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Bis 2030 überwinden („Housing First“)",
        "LINKE": "Housing First, keine Zwangsräumung" } },
      { label: "Boden- / Vorkaufspolitik", zellen: {
        "CDU/CSU": "Innenverdichtung, Brachflächen",
        "AfD": "Einheimische bevorzugen",
        "SPD": "Bodenfonds, Vorkaufsrecht",
        "GRÜNE": "Bodenfonds, Vorkaufsrecht stärken",
        "LINKE": "Re-Kommunalisierungsfonds, Vorkaufsrecht" } },
      { label: "Studierenden-/WG-Wohnen", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "WG-Zimmer max. 400 €, Wohnheime ausbauen",
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Recht auf Wohnen ins GG", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Verankern" } },
    ],
  },
  "Recht": {
    aspekte: [
      { label: "Sexualstrafrecht („Nur Ja heißt Ja“)", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Gesetzlich verankern",
        "GRÜNE": null,
        "LINKE": "Verankern" } },
      { label: "Schwangerschaftsabbruch", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Entkriminalisieren",
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Cannabis-Legalisierung", zellen: {
        "CDU/CSU": "Zurücknehmen",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Strafrecht (Verschärfen vs. Entlasten)", zellen: {
        "CDU/CSU": "Härtere Strafen für Schutzgruppen",
        "AfD": null,
        "SPD": "Gewaltschutz ausbauen",
        "GRÜNE": "Entlasten (Bagatellen auslagern)",
        "LINKE": "Sonderstrafrecht abschaffen" } },
      { label: "Direkte Demokratie", zellen: {
        "CDU/CSU": null,
        "AfD": "Volksabstimmungen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Volksentscheide auf Bundesebene" } },
      { label: "Überwachung ablehnen", zellen: {
        "CDU/CSU": null,
        "AfD": "Vorratsdaten/Staatstrojaner ablehnen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Ablehnen" } },
      { label: "Diskriminierungsschutz (Art. 3 GG)", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Um sex. Orientierung/Identität erweitern",
        "GRÜNE": null,
        "LINKE": "Erweitern" } },
      { label: "Justiz & Rechtsstaat", zellen: {
        "CDU/CSU": "Clankriminalität (Beweislastumkehr)",
        "AfD": "Scharia-„Friedensrichter“ verfolgen",
        "SPD": "Pakt für den Rechtsstaat, Digitalisierung",
        "GRÜNE": "Unabhängigkeit der Justiz, EUStA stärken",
        "LINKE": null } },
      { label: "Geschlechterquoten", zellen: {
        "CDU/CSU": null,
        "AfD": "Als verfassungswidrig abschaffen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Streikrecht", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Gewährleisten",
        "GRÜNE": null,
        "LINKE": "Ausweiten, Tarifeinheitsgesetz abschaffen" } },
      { label: "Wahlalter 16 / Wahlrecht", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Wahlalter 16, Wahlrecht nach 5 Jahren" } },
      { label: "Polygamie / Zwangsehen", zellen: {
        "CDU/CSU": null,
        "AfD": "Annullieren",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Antisemitismus-Strafrecht", zellen: {
        "CDU/CSU": "Härter, Leugnen des Existenzrechts Israels strafbar",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
    ],
  },
  "Soziale Sicherung": {
    aspekte: [
      { label: "Rentenniveau", zellen: {
        "CDU/CSU": "Über Wachstum stabil, keine Kürzung",
        "AfD": "An westeuropäisches Niveau angleichen",
        "SPD": "Mindestens 48 %",
        "GRÜNE": "Mindestens 48 %",
        "LINKE": "Auf 53 % anheben" } },
      { label: "Renteneintrittsalter", zellen: {
        "CDU/CSU": "Aktivrente (Weiterarbeit steuerfrei)",
        "AfD": "Abschlagsfrei nach 45 Beitragsjahren",
        "SPD": "Abschlagsfrei nach 45 Jahren, keine Anhebung",
        "GRÜNE": "Rente mit 63 beibehalten",
        "LINKE": null } },
      { label: "Wer zahlt ein", zellen: {
        "CDU/CSU": "Private/betriebliche Vorsorge stärken",
        "AfD": "Beamte und Politiker einbeziehen",
        "SPD": "Selbstständige einbeziehen",
        "GRÜNE": "Bürgerversicherung (auch Abgeordnete)",
        "LINKE": "Erwerbstätigenversicherung (alle)" } },
      { label: "Kapitalgedeckte Vorsorge", zellen: {
        "CDU/CSU": "Frühstart-Rente (10 €/Monat für Kinder)",
        "AfD": "Aktien-/ETF-Anreize, „Junior-Spardepot“",
        "SPD": "Betriebliche/private Förderung",
        "GRÜNE": "Öffentlicher Bürgerfonds",
        "LINKE": null } },
      { label: "Bürgergeld / Grundsicherung", zellen: {
        "CDU/CSU": "„Neue Grundsicherung“, Sanktionen",
        "AfD": "„Aktivierende Grundsicherung“, Arbeitspflicht",
        "SPD": "Aktive Arbeitsmarktpolitik",
        "GRÜNE": "Armutsvermeidend stärken",
        "LINKE": "Sanktionsfreie Mindestsicherung (~1.400 €)" } },
      { label: "Mindest- / Grundrente", zellen: {
        "CDU/CSU": null,
        "AfD": "Grundsicherung im Alter verbessern",
        "SPD": "Grundrente ausbauen",
        "GRÜNE": "Grundrente zur Garantierente",
        "LINKE": "Solidarische Mindestrente" } },
      { label: "Kindergrundsicherung", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Armutsfeste Familienleistungen",
        "GRÜNE": "Einführen (automatisiert)",
        "LINKE": "Einführen (350 € Kindergeld)" } },
      { label: "Erwerbsminderungsrente", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Ausbauen",
        "GRÜNE": "Verbessern",
        "LINKE": null } },
      { label: "Hinterbliebenenrente", zellen: {
        "CDU/CSU": "Hinzuverdienst bei Witwenrenten erhöhen",
        "AfD": null,
        "SPD": "Verbessern",
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Minijobs", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "In Sozialversicherung überführen",
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Ukraine-Flüchtlinge", zellen: {
        "CDU/CSU": null,
        "AfD": "Aus dem Bürgergeld ausgliedern",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
    ],
  },
  "Sport, Freizeit und Tourismus": {
    aspekte: [
      { label: "Sport als Staatsziel (GG)", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Verankern",
        "GRÜNE": null,
        "LINKE": "Verankern" } },
      { label: "Sportstätten sanieren", zellen: {
        "CDU/CSU": "„Sportmilliarde“ sichern",
        "AfD": null,
        "SPD": "Sanieren",
        "GRÜNE": "Bundesprogramm ausbauen",
        "LINKE": "1 Mrd. €/Jahr über 15 Jahre" } },
      { label: "Schwimmen lernen", zellen: {
        "CDU/CSU": "Alle Kinder sollen schwimmen können",
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Schwimmausbildung stärken",
        "LINKE": "Alle bis zur Primarstufe" } },
      { label: "Spitzensport", zellen: {
        "CDU/CSU": "Mehr Medaillen, bessere Trainerbedingungen",
        "AfD": null,
        "SPD": "Spitzensport-Reform",
        "GRÜNE": "Anti-Korruptions-Agentur",
        "LINKE": null } },
      { label: "Olympia-Bewerbung", zellen: {
        "CDU/CSU": "Befürworten",
        "AfD": null,
        "SPD": "Unterstützen",
        "GRÜNE": "Nur mit Menschenrechten/Nachhaltigkeit",
        "LINKE": null } },
      { label: "E-Sport", zellen: {
        "CDU/CSU": "Als gemeinnützig anerkennen",
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Als gemeinnützig anerkennen",
        "LINKE": null } },
      { label: "Gewaltschutz im Sport", zellen: {
        "CDU/CSU": "Schutz vor sexualisierter Gewalt",
        "AfD": null,
        "SPD": "Zentrum für Safe Sport",
        "GRÜNE": "Anti-Doping und Korruption",
        "LINKE": null } },
      { label: "Förderung Mädchen / queer", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Gezielt fördern",
        "LINKE": null } },
      { label: "Sportverwaltung", zellen: {
        "CDU/CSU": "Ins Kanzleramt, Staatsminister für Sport",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Gebührenfreie / inklusive Angebote", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Inklusiv gestalten",
        "LINKE": "Gebührenfrei, barrierefrei" } },
      { label: "Tourismus", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Nachhaltige Tourismusstrategie",
        "LINKE": null } },
    ],
  },
  "Staat und Verwaltung": {
    aspekte: [
      { label: "Verwaltungsdigitalisierung", zellen: {
        "CDU/CSU": "Effizienter, digitaler",
        "AfD": null,
        "SPD": "Genehmigungsfiktion, DeutschlandID/eID",
        "GRÜNE": "Deutschland-App, Once-Only-Prinzip",
        "LINKE": "Bürokratische Hürden abbauen" } },
      { label: "Schuldenbremse", zellen: {
        "CDU/CSU": "An Maastricht-Kriterien festhalten",
        "AfD": "Strikt einhalten, keine Neuverschuldung",
        "SPD": "Reformieren für Investitionen",
        "GRÜNE": "Reformieren",
        "LINKE": "Abschaffen" } },
      { label: "Kommunen / Altschulden", zellen: {
        "CDU/CSU": "Konnexitätsprinzip, klare Zuständigkeiten",
        "AfD": null,
        "SPD": "Entschulden",
        "GRÜNE": "Altschuldenfonds, mehr Spielraum",
        "LINKE": "Gemeindefinanzreform, Altschuldenfonds" } },
      { label: "Investitionsfonds", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Deutschlandfonds",
        "LINKE": null } },
      { label: "Bürokratieabbau", zellen: {
        "CDU/CSU": "Sozialausgaben-Dynamik stoppen",
        "AfD": null,
        "SPD": "Praxisgipfel, Wirksamkeitsprüfung",
        "GRÜNE": "Praxischecks, Once-Only",
        "LINKE": "Hürden für Förderprogramme abbauen" } },
      { label: "Bargeld / digitaler Euro", zellen: {
        "CDU/CSU": null,
        "AfD": "Bargeld ins GG, digitalen Euro & Vermögensregister ablehnen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Unabhängigkeit der Staatsanwaltschaft", zellen: {
        "CDU/CSU": null,
        "AfD": "Weisungsgebundenheit abschaffen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Whistleblower-Schutz", zellen: {
        "CDU/CSU": null,
        "AfD": "Schützen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Privatisierung / Daseinsvorsorge", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Infrastrukturgarantie, rekommunalisieren" } },
      { label: "Öffentlicher Dienst", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Attraktiver (Homeoffice, weniger Befristung)",
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Gewerbesteuer", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Zu Gemeindewirtschaftsteuer (Hebesatz ≥ 350 %)" } },
      { label: "Gleichwertige Lebensverhältnisse", zellen: {
        "CDU/CSU": "Stadt-/Dorfentwicklung, Daseinsvorsorge",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
    ],
  },
  "Umwelt": {
    aspekte: [
      { label: "Klimaschutz-Grundhaltung", zellen: {
        "CDU/CSU": "Emissionshandel als Leitinstrument",
        "AfD": "Klimawandel bestreiten, Paris-Ausstieg",
        "SPD": "1,5-Grad-Ziel, keine Aufweichung",
        "GRÜNE": "CO₂-Preis als zentrales Instrument",
        "LINKE": "Verbindliche Sektorziele zurück" } },
      { label: "CO₂-Preis / Klimageld", zellen: {
        "CDU/CSU": "Einnahmen zurückgeben (Klimabonus)",
        "AfD": "CO₂-Abgaben ablehnen",
        "SPD": "Klimageld als Ausgleich",
        "GRÜNE": "CO₂-Preis plus Klimageld",
        "LINKE": "Sozial abfedern, Klimageld" } },
      { label: "CO₂-Speicherung (CCS/CCU)", zellen: {
        "CDU/CSU": "Fördern",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Klimaanpassung / Hochwasser", zellen: {
        "CDU/CSU": "Naturbasierter Hochwasserschutz",
        "AfD": null,
        "SPD": "Hitzeresiliente Planung",
        "GRÜNE": "Klimaanpassungsgesetz, Schwammstadt",
        "LINKE": null } },
      { label: "Artenschutz / Biodiversität", zellen: {
        "CDU/CSU": "Schutzgebiete aufwerten",
        "AfD": "Invasive Arten, Wildbestände regulieren",
        "SPD": "Flächen schützen und vernetzen",
        "GRÜNE": "EU-Naturschutzrecht umsetzen",
        "LINKE": "Schutzgebiete ausweiten, Renaturierung" } },
      { label: "Wald", zellen: {
        "CDU/CSU": null,
        "AfD": "Nachhaltige Bewirtschaftung, nationale Hoheit",
        "SPD": null,
        "GRÜNE": "Bundeswaldgesetz, naturnahe Mischwälder",
        "LINKE": null } },
      { label: "Kreislaufwirtschaft / Plastik", zellen: {
        "CDU/CSU": "Stoffkreisläufe schließen",
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Weniger Plastik, internationales Abkommen",
        "LINKE": "Recyclingquoten, Einwegverbote" } },
      { label: "Wasser", zellen: {
        "CDU/CSU": "Gewässerschutz",
        "AfD": "Öffentliche Kontrolle über Wasserressourcen",
        "SPD": null,
        "GRÜNE": "EU-Wasserrahmenrichtlinie umsetzen",
        "LINKE": null } },
      { label: "Fossile Energie (aus Umweltsicht)", zellen: {
        "CDU/CSU": null,
        "AfD": "Fossil ohne Beschränkung",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Kohle 2030 / Erdgas 2035 raus" } },
      { label: "Klimaschädliche Subventionen", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Schrittweise abbauen",
        "LINKE": null } },
      { label: "Elementarschaden-Pflichtversicherung", zellen: {
        "CDU/CSU": "Einführen",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "EU-Umweltregulierung", zellen: {
        "CDU/CSU": null,
        "AfD": "Ablehnen (nationale Hoheit)",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
    ],
  },
  "Verkehr": {
    aspekte: [
      { label: "Tempolimit Autobahn", zellen: {
        "CDU/CSU": "Ablehnen",
        "AfD": "Ablehnen",
        "SPD": "130 km/h",
        "GRÜNE": "130 km/h",
        "LINKE": "120 km/h" } },
      { label: "Tempo 30 innerorts", zellen: {
        "CDU/CSU": null,
        "AfD": "Ablehnen",
        "SPD": null,
        "GRÜNE": "Flächendeckend ermöglichen",
        "LINKE": "Tempo 30 (außer Hauptachsen)" } },
      { label: "Verbrenner / E-Mobilität", zellen: {
        "CDU/CSU": "Verbrenner-Verbot zurücknehmen, technologieoffen",
        "AfD": "Verbrenner und E-Fuels, gegen E-Auto-Förderung",
        "SPD": "E-Auto-Förderung, Ladeinfrastruktur",
        "GRÜNE": "Antriebswende",
        "LINKE": "Am Verbrenner-Aus festhalten" } },
      { label: "Deutschlandticket / ÖPNV-Preis", zellen: {
        "CDU/CSU": null,
        "AfD": "Zum „ehrlichen Preis“",
        "SPD": "Dauerhaft, sozial vergünstigt",
        "GRÜNE": "49 €, vergünstigt für Gruppen",
        "LINKE": "9-Euro-Ticket, perspektivisch kostenfrei" } },
      { label: "Schiene ausbauen", zellen: {
        "CDU/CSU": "Bund finanziert Infrastruktur",
        "AfD": "Nach Schweizer Vorbild",
        "SPD": "Rekordinvestitionen",
        "GRÜNE": "Netz ausbauen, Fahrgäste verdoppeln",
        "LINKE": "Gemeinnützig, bis 2030 verdoppeln" } },
      { label: "Bahnstruktur / Eigentum", zellen: {
        "CDU/CSU": "Infrastruktur und Transport trennen",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "ÖPNV in öffentliche Hand zurückholen" } },
      { label: "Rad- & Fußverkehr", zellen: {
        "CDU/CSU": "Radwege ausbauen",
        "AfD": null,
        "SPD": "Vision Zero, Radinfrastruktur",
        "GRÜNE": "Priorisieren",
        "LINKE": null } },
      { label: "Güterverkehr auf die Schiene", zellen: {
        "CDU/CSU": "Schiene und Wasserstraßen stärken",
        "AfD": "„Rollende Landstraße“",
        "SPD": "Auf die Schiene verlagern",
        "GRÜNE": "Antriebswende im Güterverkehr",
        "LINKE": "Auf Schiene/Binnenschiff verlagern" } },
      { label: "Luftverkehr", zellen: {
        "CDU/CSU": null,
        "AfD": "Luftverkehrsteuer abschaffen, keine Flugverbote",
        "SPD": "EU-Klimaabgabe",
        "GRÜNE": "Kurzstreckenflüge überflüssig machen, Privatjet-Privilegien streichen",
        "LINKE": "Privatjets/Kurzstreckenflüge verbieten, Vielfliegersteuer" } },
      { label: "Straßenbau / Sanierung", zellen: {
        "CDU/CSU": "Sanieren, private Investoren",
        "AfD": "Autobahnen und Brücken sanieren",
        "SPD": "Sanierung priorisieren",
        "GRÜNE": "Sanierung vor Neubau",
        "LINKE": "Kein Autobahnneubau" } },
      { label: "Lkw-Maut", zellen: {
        "CDU/CSU": null,
        "AfD": "CO₂-Maut-Erhöhung zurücknehmen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Dienstwagenprivileg", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Abschaffen" } },
    ],
  },
  "Verteidigung": {
    aspekte: [
      { label: "NATO", zellen: {
        "CDU/CSU": "Uneingeschränkt",
        "AfD": "Zentral, aber keine US-Waffen in DE",
        "SPD": "Zentraler Pfeiler",
        "GRÜNE": "Fest integriert",
        "LINKE": "Ablehnen" } },
      { label: "Verteidigungsausgaben (2 %)", zellen: {
        "CDU/CSU": "2 % als Untergrenze",
        "AfD": null,
        "SPD": "Mindestens 2 %",
        "GRÜNE": "Dauerhaft über 2 %",
        "LINKE": "2-%-Ziel ablehnen, senken" } },
      { label: "Wehrpflicht / Wehrdienst", zellen: {
        "CDU/CSU": "Gesellschaftsjahr + aufwachsende Wehrpflicht",
        "AfD": "Wehrpflicht wieder einführen",
        "SPD": "Neuer freiwilliger Wehrdienst",
        "GRÜNE": "Freiwilligen Wehrdienst attraktiver",
        "LINKE": null } },
      { label: "Nukleare Teilhabe", zellen: {
        "CDU/CSU": "Unverzichtbar",
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Vorerst beibehalten",
        "LINKE": "Beenden, US-Atomwaffen abziehen" } },
      { label: "Truppenstärke / Ausstattung", zellen: {
        "CDU/CSU": "180.000 → 203.000",
        "AfD": "Personell/materiell stärken",
        "SPD": "Prioritär ausstatten",
        "GRÜNE": "Besser ausstatten",
        "LINKE": "Zu reiner Verteidigungsarmee umbauen" } },
      { label: "Rüstungsindustrie / Beschaffung", zellen: {
        "CDU/CSU": "EU-Binnenmarkt, Technologieführerschaft",
        "AfD": "Autonome wehrtechnische Industrie",
        "SPD": "Gemeinsame EU-Beschaffung",
        "GRÜNE": "Europäische Rüstungskooperation",
        "LINKE": "Rüstungsbetriebe vergesellschaften" } },
      { label: "Rüstungsexporte", zellen: {
        "CDU/CSU": null,
        "AfD": "Keine Materialabgaben an die Ukraine",
        "SPD": null,
        "GRÜNE": "Völkerrechtskonform",
        "LINKE": "Vollständig verbieten" } },
      { label: "Autonome Waffen / Cyber", zellen: {
        "CDU/CSU": "Drohnen, Cyber, Weltraum",
        "AfD": "Offensive Cyberfähigkeiten",
        "SPD": null,
        "GRÜNE": "Autonome Waffen ächten",
        "LINKE": null } },
      { label: "Abrüstung", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "New START, „No first use“",
        "GRÜNE": "Atomwaffenfreie Welt",
        "LINKE": "Rüstung senken, kollektive Abrüstung" } },
      { label: "Zivilschutz", zellen: {
        "CDU/CSU": null,
        "AfD": "Schutzräume ausbauen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Auslandseinsätze", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Völkerrechtskonform, multilateral",
        "LINKE": "Bundeswehr abziehen" } },
    ],
  },
  "Wissenschaft, Forschung und Technologie": {
    aspekte: [
      { label: "Forschungsinvestitionen", zellen: {
        "CDU/CSU": "F&E auf 3,5 % des BIP bis 2030",
        "AfD": "Gegen Subventionen, gezielt",
        "SPD": "KI, Quanten, Robotik",
        "GRÜNE": "Deutlich über 3,5 %",
        "LINKE": null } },
      { label: "Arbeitsbedingungen Wissenschaft", zellen: {
        "CDU/CSU": "Mehr Freiräume",
        "AfD": "Mehr Autonomie der Hochschulen",
        "SPD": "Planbare Karrierewege",
        "GRÜNE": "Weniger Befristung",
        "LINKE": "Dauerstellen, Kettenbefristungen beenden" } },
      { label: "Grundfinanzierung vs. Drittmittel", zellen: {
        "CDU/CSU": null,
        "AfD": "Drittmittelabhängigkeit verringern",
        "SPD": null,
        "GRÜNE": "Auskömmliche Grundfinanzierung",
        "LINKE": "Grundfinanzierung statt Drittmittel" } },
      { label: "Zukunftstechnologien", zellen: {
        "CDU/CSU": "Hightech-Agenda (Quanten, KI, Fusion)",
        "AfD": "Luft-/Raumfahrt, Kerntechnik",
        "SPD": "KI-Strategie",
        "GRÜNE": "KI, Quanten, Mikrochips",
        "LINKE": null } },
      { label: "Transfer / Start-ups", zellen: {
        "CDU/CSU": "Patent- und Ausgründungsstrategie",
        "AfD": null,
        "SPD": "Inkubatoren, Cluster",
        "GRÜNE": "Reallabore, Innovationsökosysteme",
        "LINKE": null } },
      { label: "Forschungsfreiheit / Entpolitisierung", zellen: {
        "CDU/CSU": null,
        "AfD": "Entpolitisieren, Genderforschung nicht finanzieren",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Offener Datenzugang / Transparenz", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Forschungsdatengesetz",
        "LINKE": "Hochschul-Wirtschafts-Verträge offenlegen" } },
      { label: "Studiengänge (Bologna)", zellen: {
        "CDU/CSU": null,
        "AfD": "Diplom/Magister zurück",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Zivilklauseln / Friedensforschung", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Verankern" } },
      { label: "Internationaler Austausch", zellen: {
        "CDU/CSU": "Kooperationen (Israel, USA, EU)",
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Schnellere Visa",
        "LINKE": "Schutz verfolgter Wissenschaftler:innen" } },
    ],
  },
  "Öffentliche Finanzen, Steuern und Abgaben": {
    aspekte: [
      { label: "Schuldenbremse", zellen: {
        "CDU/CSU": "Maastricht-Kriterien verbindlich",
        "AfD": "Strikt, keine Neuverschuldung",
        "SPD": "Reformieren für Investitionen",
        "GRÜNE": "Reformieren (Investitionskredite)",
        "LINKE": "Abschaffen" } },
      { label: "Einkommensteuer", zellen: {
        "CDU/CSU": "Abflachen, kalte Progression ausgleichen",
        "AfD": "Keine Erhöhung",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "Spitzensteuer bis 75 %" } },
      { label: "Vermögensteuer", zellen: {
        "CDU/CSU": null,
        "AfD": "Abschaffen",
        "SPD": "Revitalisieren",
        "GRÜNE": null,
        "LINKE": "Ab 1 Mio. € (bis 12 %)" } },
      { label: "Erbschaftsteuer", zellen: {
        "CDU/CSU": null,
        "AfD": "Abschaffen",
        "SPD": "Höher besteuern",
        "GRÜNE": null,
        "LINKE": "Bis 60 %" } },
      { label: "Kapital- / Unternehmenssteuern", zellen: {
        "CDU/CSU": null,
        "AfD": "Sparerpauschbetrag erhöhen",
        "SPD": "Mindestbesteuerung großer Betriebe",
        "GRÜNE": "Digitalkonzernsteuer",
        "LINKE": "Kapital wie Arbeit besteuern" } },
      { label: "Finanztransaktionssteuer", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Einführen",
        "GRÜNE": null,
        "LINKE": "0,1 %" } },
      { label: "Übergewinnsteuer", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": "90 % auf Krisenprofite" } },
      { label: "Sozialbeiträge", zellen: {
        "CDU/CSU": "Auf 40 % begrenzen",
        "AfD": "Zweckentfremdung beenden",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "Familiensplitting", zellen: {
        "CDU/CSU": null,
        "AfD": "Einführen",
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "EU-Finanzen", zellen: {
        "CDU/CSU": "EU-Mittel nur mit Mehrwert",
        "AfD": "Kein EU-Besteuerungsrecht, weniger Beiträge",
        "SPD": "Echte Eigenmittel",
        "GRÜNE": "Neue Eigenmittel, größerer Finanzrahmen",
        "LINKE": null } },
      { label: "Steuervereinfachung / Bürokratie", zellen: {
        "CDU/CSU": "„One in, two out“, einfacheres Steuerrecht",
        "AfD": null,
        "SPD": null,
        "GRÜNE": null,
        "LINKE": null } },
      { label: "CO₂-Einnahmen / Klimageld", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": null,
        "GRÜNE": "Als sozial gestaffeltes Klimageld",
        "LINKE": null } },
      { label: "Steuerhinterziehung bekämpfen", zellen: {
        "CDU/CSU": null,
        "AfD": null,
        "SPD": "Stärkere Behörde",
        "GRÜNE": null,
        "LINKE": "Mehr Fahndung, Unternehmensstrafrecht" } },
    ],
  },
  "Wirtschaft": {
    aspekte: [
      {
        label: "Rolle des Staates / Wirtschaftsordnung",
        zellen: {
          "CDU/CSU": "Soziale Marktwirtschaft, Wettbewerbsfähigkeit stärken",
          "AfD": "Soziale Marktwirtschaft, Staatseingriffe aufs Minimum",
          "SPD": "Wachstum, soziale Gerechtigkeit und Nachhaltigkeit verbinden",
          "GRÜNE": "Klimaneutrale Modernisierung der Industrie",
          "LINKE": "Sozial-ökologischer Umbau unter staatlicher Steuerung",
        },
      },
      {
        label: "Unternehmenssteuern",
        zellen: {
          "CDU/CSU": "Körperschaftsteuer auf max. 25 %, Soli abschaffen",
          "AfD": "Steuer- und Abgabenlast senken",
          "SPD": "Keine generelle Senkung",
          "GRÜNE": null,
          "LINKE": null,
        },
      },
      {
        label: "Steuerliche Investitionsanreize",
        zellen: {
          "CDU/CSU": "Anreize für Mittelstand (z. B. Cybersecurity)",
          "AfD": null,
          "SPD": "10 % Investitionsprämie, bessere Abschreibung E-Mobilität",
          "GRÜNE": null,
          "LINKE": null,
        },
      },
      {
        label: "Staatliche Investitionsfonds",
        zellen: {
          "CDU/CSU": null,
          "AfD": "Lehnt Subventionen ab",
          "SPD": "„Deutschlandfonds“, 100 Mrd. €",
          "GRÜNE": "Gezielte Investitionsförderung",
          "LINKE": "200 Mrd. € Fonds + 65 Mrd. €/Jahr Transformation",
        },
      },
      {
        label: "Bürokratie abbauen",
        zellen: {
          "CDU/CSU": "„One in, two out“, Verfallsdaten für Gesetze",
          "AfD": "Bürokratie und Regulierung abbauen",
          "SPD": "Ja, bei gewahrten Arbeitnehmerrechten",
          "GRÜNE": "Für Mittelstand/Handwerk, kostenlose Meisterbriefe",
          "LINKE": null,
        },
      },
      {
        label: "Energiekosten für die Wirtschaft",
        zellen: {
          "CDU/CSU": "Neue Rohstoff- und Energieabkommen",
          "AfD": "Bezahlbar durch Technologieoffenheit (Kernkraft, fossil)",
          "SPD": "Energiepreise senken, Netzentgelte deckeln",
          "GRÜNE": "CO₂-Preis plus Klimaschutzverträge",
          "LINKE": null,
        },
      },
      {
        label: "Subventionen für grüne Technik / E-Mobilität",
        zellen: {
          "CDU/CSU": null,
          "AfD": "Abschaffen (nicht marktfähige Technologien)",
          "SPD": "Abschreibungsvorteile für E-Mobilität",
          "GRÜNE": "Fördern (Klimaschutzverträge, grüner Stahl)",
          "LINKE": null,
        },
      },
      {
        label: "Außenhandel",
        zellen: {
          "CDU/CSU": "Freihandel, gegen Protektionismus",
          "AfD": "Diskriminierungsfrei; Lieferkettengesetz ablehnen",
          "SPD": "EU-Binnenmarkt stärken",
          "GRÜNE": "Abkommen mit verbindlichen Öko-/Sozialstandards",
          "LINKE": "Regionale Kreisläufe, kurze Lieferketten",
        },
      },
      {
        label: "Lieferketten & Rohstoffsicherheit",
        zellen: {
          "CDU/CSU": "Diversifizieren (Halbleiter, Batteriezellen)",
          "AfD": null,
          "SPD": null,
          "GRÜNE": "Rohstoffsicherheit (4 Säulen), Kreislaufwirtschaft",
          "LINKE": null,
        },
      },
      {
        label: "Forschung & Innovation",
        zellen: {
          "CDU/CSU": "F&E auf 3,5 % des BIP bis 2030",
          "AfD": "F&E in traditionellen und Hochtechnologiebranchen",
          "SPD": null,
          "GRÜNE": "KI, Quantencomputing, klimaneutrale Energie",
          "LINKE": "Patente auf klimarelevante Technik öffentlich",
        },
      },
      {
        label: "Start-up-Förderung",
        zellen: {
          "CDU/CSU": "Gründerschutzzonen, Ausgründungen aus der Wissenschaft",
          "AfD": null,
          "SPD": null,
          "GRÜNE": "Bessere Finanzierung, unterrepräsentierte Gründer",
          "LINKE": null,
        },
      },
      {
        label: "Mittelstand & Handwerk",
        zellen: {
          "CDU/CSU": "Förderzugang vereinfachen, entlasten",
          "AfD": "Mittelstand stärken",
          "SPD": "Mittelstand und Landwirtschaft unterstützen",
          "GRÜNE": "Bürokratieabbau, Meisterbriefe, Nachfolge",
          "LINKE": null,
        },
      },
      {
        label: "Mitbestimmung der Beschäftigten",
        zellen: {
          "CDU/CSU": null,
          "AfD": null,
          "SPD": "Arbeitnehmerrechte wahren",
          "GRÜNE": "Mitarbeiterkapitalbeteiligung ausbauen",
          "LINKE": "Veto-Rechte für Betriebsräte",
        },
      },
      {
        label: "Förderung an Bedingungen knüpfen",
        zellen: {
          "CDU/CSU": null,
          "AfD": null,
          "SPD": null,
          "GRÜNE": "Klimaschutzverträge an Tarifbindung",
          "LINKE": "Fördergeld an Tarifbindung und Standortgarantien",
        },
      },
      {
        label: "Öffentliches Eigentum / Vergesellschaftung",
        zellen: {
          "CDU/CSU": null,
          "AfD": null,
          "SPD": null,
          "GRÜNE": null,
          "LINKE": "Schlüsselbranchen vergesellschaften, Auto-Produktion",
        },
      },
      {
        label: "Schutz vor ausländischen Übernahmen",
        zellen: {
          "CDU/CSU": null,
          "AfD": "Schlüsselindustrien vor Übernahmen schützen",
          "SPD": null,
          "GRÜNE": null,
          "LINKE": null,
        },
      },
      {
        label: "Geistiges Eigentum / Produktpiraterie",
        zellen: {
          "CDU/CSU": "Schutz geistigen Eigentums, gegen Produktpiraterie",
          "AfD": null,
          "SPD": null,
          "GRÜNE": null,
          "LINKE": null,
        },
      },
      {
        label: "Export-Förderung",
        zellen: {
          "CDU/CSU": "Staatliche Garantien, schnellere Ausfuhrgenehmigungen",
          "AfD": null,
          "SPD": null,
          "GRÜNE": null,
          "LINKE": null,
        },
      },
      {
        label: "Kartellrecht / Wettbewerbsaufsicht",
        zellen: {
          "CDU/CSU": "Kartellamt-Eingriffe an Rechtsverstöße binden",
          "AfD": null,
          "SPD": null,
          "GRÜNE": null,
          "LINKE": null,
        },
      },
      {
        label: "Währungspolitik",
        zellen: {
          "CDU/CSU": null,
          "AfD": "Rückkehr zu nationalen Währungen",
          "SPD": null,
          "GRÜNE": null,
          "LINKE": null,
        },
      },
      {
        label: "Fachkräftesicherung",
        zellen: {
          "CDU/CSU": null,
          "AfD": null,
          "SPD": "Qualifizierung, Zuwanderung, inländische Potenziale",
          "GRÜNE": null,
          "LINKE": "Weiterbildungsgeld (90 %) im Strukturwandel",
        },
      },
    ],
  },
};

export function getFeldMatrix(feld: string): FeldMatrix | null {
  return VERGLEICH_MATRIX[feld] ?? null;
}
