/**
 * BT-Themen-Struktur fürs UI: 14 Anzeige-Oberthemen (User+Gemini 2026-06-12)
 * über den 25 Klassifikations-Feldern mit ihren 202 Unterthemen.
 * Daten-Korn = ds_unterthemen (feld, unterthema) — die Gruppierung hier ist
 * reine ANZEIGE-Entscheidung (jederzeit änderbar, kein Re-Lauf nötig).
 * GENERIERT aus docs/themen-taxonomie-bt.md.
 */
export const TAXONOMIE: Record<string, readonly string[]> = {
  "Wirtschaft": [
    "Industrie- & Standortpolitik",
    "Außenhandel, Zölle & Rohstoffe",
    "Digital- & KI-Wirtschaft",
    "Energiewirtschaft & Energiekosten",
    "Lieferketten & Unternehmensverantwortung",
    "Wirtschaftsförderung & Subventionen",
    "Mittelstand, Handwerk & Gründung",
    "Fachkräfte & Arbeitsmarkt-Wirtschaft",
    "Verbraucherschutz",
    "Konjunktur, Wachstum & Gesamtsteuerung",
    "Wettbewerb & Kartellrecht",
  ],
  "Innere Sicherheit": [
    "Extremismus & Verfassungsschutz",
    "Kriminalitätslage & Kriminalstatistik",
    "Polizei, Befugnisse & Überwachung",
    "Cybersicherheit, Spionage & hybride Bedrohungen",
    "Hasskriminalität & Schutz gefährdeter Gruppen",
    "Terrorismus & Islamismus",
    "Gewaltschutz & Sexualdelikte",
    "Wirtschafts- & Finanzkriminalität",
    "Bevölkerungsschutz, Waffenrecht & öffentliche Ordnung",
  ],
  "Öffentliche Finanzen, Steuern und Abgaben": [
    "Steuerpolitik & Steuerrecht",
    "Bundeshaushalt, Schulden & Sondervermögen",
    "Steuervollzug, Zoll & Finanzkriminalität",
    "Finanzmarkt, Banken & Finanzaufsicht",
    "Öffentliche Ausgaben & Behördenkosten-Transparenz",
    "Förderprogramme, Zuwendungen & Bürgschaften",
    "Bund-Länder- & Kommunalfinanzen",
    "EU- & internationale Finanzpolitik",
  ],
  "Recht": [
    "Strafrecht & Strafverfahren",
    "Strafverfolgung, Kriminalstatistik & Wirtschaftskriminalität",
    "Strafvollzug & Strafvollstreckung",
    "Opferschutz & Gewaltschutz",
    "Zivil-, Familien- & Verbraucherrecht",
    "Justizsystem, Gerichte & Digitalisierung der Justiz",
    "Rechtsangelegenheiten & Rechtspolitik der Bundesbehörden",
  ],
  "Staat und Verwaltung": [
    "Transparenz, Informationsfreiheit & Aktenzugang",
    "Lobbyismus & Interessenkonflikte",
    "Externe Beratung, Gutachten & Regierungskommunikation",
    "Staatliche Förderungen & Zuwendungskontrolle",
    "Bürokratieabbau & Verwaltungsvereinfachung",
    "Digitale Verwaltung & Register",
    "Parlament, Wahlen & Geschäftsordnung",
    "Bundesbehörden, Personal & Ressortberichte",
  ],
  "Medien, Kommunikation und Informationstechnik": [
    "Digitale Verwaltung, Justiz & Staatsmodernisierung",
    "Cybersicherheit & kritische Infrastrukturen",
    "Plattformen, digitale Dienste & Online-Werbung",
    "Datenschutz, Überwachung & Bürgerrechte",
    "KI & digitale Infrastruktur",
    "Online-Kriminalität, Deepfakes & digitale Gewalt",
    "Krypto-Regulierung & digitale Finanzen",
  ],
  "Gesundheit": [
    "Corona-Aufarbeitung, Impfen & Pandemiefolgen",
    "Infektionsschutz & öffentlicher Gesundheitsdienst",
    "Krankenhäuser & Versorgungsstrukturen",
    "Notfall- & Rettungsversorgung, Krisenresilienz",
    "Prävention, Ernährung & Umweltgesundheit",
    "Psychische Gesundheit, Sucht & Cannabis",
    "Arzneimittel, Apotheken & Medizinprodukte",
    "Pflege",
    "Kranken- & Pflegeversicherung: Finanzierung & Beiträge",
  ],
  "Umwelt": [
    "Klimapolitik, Klimaziele & CO₂-Speicherung",
    "Klimaanpassung, Wasser & Extremwetter",
    "Naturschutz, Artenvielfalt & Wildtiere",
    "Meeres- & Gewässerschutz",
    "Kreislaufwirtschaft, Abfall & Recycling",
    "Chemikalien, Luftreinhaltung & Altlasten",
    "Atommüll, Endlager & nukleare Sicherheit",
    "Umweltrecht, Verbände & Genehmigungsverfahren",
  ],
  "Energie": [
    "Erneuerbarer Strom: Wind, Solar & EEG",
    "Stromnetze, Netzausbau & Systemstabilität",
    "Energiepreise, Energiesteuern & Entlastungen",
    "Gasversorgung, LNG & Import-Geopolitik",
    "Kernenergie & nukleare Brennstoffkette",
    "Wasserstoff, Bioenergie & erneuerbare Gase",
    "Versorgungssicherheit & kritische Infrastruktur",
    "Wärmewende & Gebäudeenergie",
    "Kraftwerke, Kohleausstieg & Staatsbeteiligungen",
  ],
  "Landwirtschaft und Ernährung": [
    "Agrarförderung, GAP & ländliche Entwicklung",
    "Pflanzenschutz, Düngung & Pflanzenbau",
    "Tierhaltung, Tierschutz & Stallumbau",
    "Tiergesundheit & Tierseuchen",
    "Wolf, Jagd & Wildtiermanagement",
    "Agrarmärkte, Erzeugerpreise & Lieferketten",
    "Ernährungspolitik, Lebensmittelsicherheit & Kennzeichnung",
    "Flächen, Boden & Ernährungssicherung",
    "Betriebe, Agrarsoziales, Steuern & Bürokratie",
  ],
  "Außenpolitik und internationale Beziehungen": [
    "Naher Osten (Israel/Gaza, Iran, Syrien)",
    "Ukraine, Russland & Sanktionen",
    "Außenwirtschaft, Handel & Rohstoffe",
    "Menschenrechte & bilaterale Länderbeziehungen",
    "Auswärtiger Dienst, Kultur- & Bildungsaußenpolitik",
    "UN, NATO & internationale Organisationen",
    "Bundeswehr-Auslandseinsätze & Missionsmandate",
    "Rüstungsexporte & Waffenexportkontrolle",
  ],
  "Europapolitik und Europäische Union": [
    "Deutsch-französische & Nachbarschafts-Kooperation",
    "Umsetzung von EU-Recht in deutsches Recht",
    "Laufende EU-Regulierung & deutsche Verhandlungsposition",
    "Euro, Bankenunion & Finanzstabilität",
    "EU-Dokumente & parlamentarische Europa-Befassung",
    "EU-Haushalt, Fonds & Förderprogramme",
    "Subsidiarität & Kompetenzverteilung",
    "EU-Asyl, Grenzen & Freizügigkeit",
  ],
  "Entwicklungspolitik": [
    "Projekt-Transparenz, Mittelkontrolle & Evaluierung",
    "Durchführungsorganisationen, Stiftungen & NGOs",
    "ODA-Finanzierung, Haushalt & Schulden",
    "Flucht, humanitäre Hilfe & Wiederaufbau",
    "Gender, Frauen & LGBTIQ in der EZ",
    "Bildung, Ausbildung & Freiwilligendienste",
    "Multilaterale EZ, Entwicklungsbanken & globale Gesundheit",
    "Handel, Wirtschaftspartnerschaften & Rohstoffe",
  ],
  "Arbeit und Beschäftigung": [
    "Mindestlohn & Schwarzarbeitskontrolle",
    "Tarifbindung, Gewerkschaften & Mitbestimmung",
    "Grundsicherung, Jobcenter & Arbeitsvermittlung",
    "Fachkräfte, Qualifizierung & Weiterbildung",
    "Arbeitsschutz & Arbeitsbedingungen",
    "Erwerbsbeteiligung, Arbeitszeit & Vereinbarkeit",
    "Arbeitsmarktintegration & Sprachförderung Geflüchteter",
  ],
  "Soziale Sicherung": [
    "Rente & Alterssicherung",
    "Grundsicherung & Bürgergeld (Leistungsseite)",
    "Kranken- & Pflegeversicherung",
    "Armut & Lebenshaltungskosten",
    "Sozialleistungen für Geflüchtete & AsylbLG",
    "Teilhabe & Behinderung",
    "Engagement, Freiwilligendienste & soziale Hilfesysteme",
    "Sozialversicherung: Beiträge, Status & Verwaltung",
  ],
  "Bildung und Erziehung": [
    "Frühkindliche Bildung, Kita & Ganztag",
    "Schule, Schulklima & Gewaltprävention",
    "Lehrkräfte, Unterricht & digitale Bildung",
    "Berufliche Aus- & Weiterbildung",
    "Studienfinanzierung & BAföG",
    "Hochschule, Wissenschaft & Forschungsnachwuchs",
    "Integrations- & Sprachkurse",
    "Politische Bildung, Demokratieförderung & Erinnerungskultur",
    "Kinder- & Jugendhilfe & Freiwilligendienste",
  ],
  "Migration und Aufenthaltsrecht": [
    "Abschiebung, Rückführung & Ausreisepflicht",
    "Asylverfahren & Schutzstatus",
    "Sozialleistungen, Gesundheit & Unterbringung",
    "Arbeits- & Bildungsmigration",
    "Integrationskurse & Integrationsförderung",
    "Humanitäre Aufnahme & Aufnahmeprogramme",
    "Einbürgerung & Staatsangehörigkeit",
    "Familiennachzug & Aufenthaltstitel",
    "Grenze & irreguläre Migration",
  ],
  "Verkehr": [
    "Schienennetz, Bahnprojekte & Sanierung",
    "Straßenbau, Autobahnen & Brücken",
    "Wasserstraßen, Schifffahrt & Häfen",
    "E-Mobilität, Antriebe & Ladeinfrastruktur",
    "ÖPNV, Fahrgäste & Bahnhofsservice",
    "Straßenverkehrsrecht, Führerschein & Verkehrssicherheit",
    "Güterverkehr, Logistik & Maut",
    "Rad- & Fußverkehr",
  ],
  "Raumordnung, Bau- und Wohnungswesen": [
    "Wohnkosten, Sozialer Wohnungsbau & Wohnraumversorgung",
    "Mietrecht & Mieterschutz",
    "Kommunalfinanzen & kommunale Investitionen",
    "Wohnungsbau, Baurecht & Planungsbeschleunigung",
    "Gebäudeenergie, Heizung & Sanierung",
    "Bundesliegenschaften, Konversion & öffentliches Bauen",
    "Immobilien- & Wohnungssteuern",
  ],
  "Verteidigung": [
    "Rüstungsexporte & Exportkontrolle",
    "Abrüstung, Rüstungskontrolle & Kampfmittelräumung",
    "Auslandseinsätze & Mandate",
    "Ukraine-Unterstützung & Militärhilfe",
    "Personal, Wehrdienst & Veteranen",
    "Verteidigungshaushalt, Beschaffung & Rüstungsindustrie",
    "NATO, Bündnis & Stationierung",
    "Zivilverteidigung, Übungen & hybride Bedrohungen",
  ],
  "Gesellschaftspolitik, soziale Gruppen": [
    "Gleichstellung & Frauen in Führung",
    "Gewaltschutz & geschlechtsspezifische Gewalt",
    "Antisemitismus, Rassismus & Hasskriminalität",
    "Demokratie- & Antidiskriminierungs-Förderung",
    "Familienleistungen & Demografie",
    "Familienrecht & reproduktive Selbstbestimmung",
    "Kinder- & Jugendschutz, Jugendhilfe & Betreuung",
    "Inklusion & Barrierefreiheit",
    "Engagement, Ehrenamt & Freiwilligendienste",
  ],
  "Politisches Leben, Parteien": [
    "NGO-, Zivilgesellschafts- & Demokratieförderung",
    "Parlament: Geschäftsordnung, Gremien & Abgeordnetenrecht",
    "Regierungstransparenz & parlamentarisches Fragerecht",
    "Wahlen, Wahlrecht & Wahlprüfung",
    "Parteien: Finanzierung, Organisationen & parteinahe Stiftungen",
    "Lobbyismus & Interessenkonflikte",
    "Demokratiegeschichte, Gedenken & DDR-Aufarbeitung",
    "Immunität & Verfahren gegen Abgeordnete",
  ],
  "Wissenschaft, Forschung und Technologie": [
    "Forschungsförderung, Innovationsstrategie & -agenturen",
    "Gesundheits- & Medizinforschung",
    "Energie-, Klima- & Umweltforschung",
    "KI, Digital- & Schlüsseltechnologien",
    "Internationale Wissenschaftskooperation & EU-Forschungsraum",
    "Wissenschaftsfreiheit, -integrität & Wissenschaftsrecht",
    "Sicherheits- & Verteidigungsforschung, Forschungssicherheit",
    "Raumfahrt & Weltraum",
    "Forschungsdaten & Dateninfrastruktur",
  ],
  "Kultur": [
    "Erinnerungskultur, Gedenkstätten & Kriegsgräber",
    "Medien- & Plattformpolitik",
    "Kulturförderung & Kulturpreise",
    "Kulturgutschutz, Restitution & Kolonialerbe",
    "Film, Musik & Kreativwirtschaft",
    "Kultureinrichtungen, Museen & Bibliotheken",
    "Auswärtige Kulturpolitik & internationaler Austausch",
  ],
  "Sport, Freizeit und Tourismus": [
    "Olympiabewerbungen & Sportgroßveranstaltungen",
    "Spitzensport: Förderung, Reform & Athlet:innen",
    "Sportstätten & Bäder",
    "Teilhabe, Fairness & Schutz im Sport",
  ],
};

export interface Oberthema { name: string; slug: string; felder: readonly string[] }

export const OBERTHEMEN: readonly Oberthema[] = [
  { name: "Innere Sicherheit & Recht", slug: "innere-sicherheit-recht", felder: ["Innere Sicherheit", "Recht"] },
  { name: "Staat, Verwaltung & Demokratie", slug: "staat-verwaltung-demokratie", felder: ["Staat und Verwaltung", "Politisches Leben, Parteien"] },
  { name: "Außen, Verteidigung & Europa", slug: "aussen-verteidigung-europa", felder: ["Außenpolitik und internationale Beziehungen", "Europapolitik und Europäische Union", "Entwicklungspolitik", "Verteidigung"] },
  { name: "Finanzen, Steuern & Haushalt", slug: "finanzen-steuern-haushalt", felder: ["Öffentliche Finanzen, Steuern und Abgaben"] },
  { name: "Umwelt, Klima & Energie", slug: "umwelt-klima-energie", felder: ["Umwelt", "Energie"] },
  { name: "Arbeit & Soziales", slug: "arbeit-soziales", felder: ["Arbeit und Beschäftigung", "Soziale Sicherung"] },
  { name: "Verkehr, Bauen & Wohnen", slug: "verkehr-bauen-wohnen", felder: ["Verkehr", "Raumordnung, Bau- und Wohnungswesen"] },
  { name: "Migration & Integration", slug: "migration-integration", felder: ["Migration und Aufenthaltsrecht"] },
  { name: "Wirtschaft, Handel & Industrie", slug: "wirtschaft-handel-industrie", felder: ["Wirtschaft"] },
  { name: "Bildung & Wissenschaft", slug: "bildung-wissenschaft", felder: ["Bildung und Erziehung", "Wissenschaft, Forschung und Technologie"] },
  { name: "Gesundheit & Pflege", slug: "gesundheit-pflege", felder: ["Gesundheit"] },
  { name: "Digitalisierung & Netzpolitik", slug: "digitalisierung-netzpolitik", felder: ["Medien, Kommunikation und Informationstechnik"] },
  { name: "Gesellschaft, Kultur & Sport", slug: "gesellschaft-kultur-sport", felder: ["Gesellschaftspolitik, soziale Gruppen", "Kultur", "Sport, Freizeit und Tourismus"] },
  { name: "Landwirtschaft & Ernährung", slug: "landwirtschaft-ernaehrung", felder: ["Landwirtschaft und Ernährung"] },
];

// Unterthema-Slug (URL) — deterministisch aus dem Cluster-Namen
export function unterSlug(s: string): string {
  return s.toLowerCase()
    .replace(/ä/g, "ae").replace(/ö/g, "oe").replace(/ü/g, "ue").replace(/ß/g, "ss")
    .replace(/[^a-z0-9]+/g, "-").replace(/^-|-$/g, "");
}

// Slug → (feld, unterthema) auflösen (über alle Felder eines Oberthemas)
export function resolveUnter(oberSlug: string, slug: string): { feld: string; unterthema: string } | null {
  const ot = OBERTHEMEN.find((o) => o.slug === oberSlug);
  if (!ot) return null;
  for (const feld of ot.felder) {
    for (const u of TAXONOMIE[feld] ?? []) {
      if (unterSlug(u) === slug) return { feld, unterthema: u };
    }
  }
  return null;
}
