export interface KommissionSeed {
  slug: string;
  name: string;
  kurzname: string | null;
  ministerium: string;
  tier: 1 | 2;
  thema: string;
  quelleUrl: string;
  pollUrl: string | null;          // null = keine scrapebare Berichtsseite (nur Anzeige via quelleUrl)
  cadence: string;
  nextExpected: string;
  status: "laufend" | "bericht_vorgelegt" | "aufgeloest";
  letzterBerichtUrl: string | null; // null = unbestätigt → kein Seed-Bericht
  // Kuratierte, UNTERSCHEIDENDE Stichwort-Phrasen für die News-Zuordnung (Substring, lowercase).
  // BEWUSST spezifisch — generische Wörter (kommission/gutachten/bericht) gehören NICHT hierher,
  // sonst landet jede „die Kommission"-Schlagzeile bei allen Gremien (Fuzzy-Matching war genau
  // dieser Fehler). Lieber präzise als breit.
  keywords: string[];
  notiz: string | null;
}

export const KOMMISSIONEN_WATCHLIST: KommissionSeed[] = [
  // ── TIER 1 — Watchlist-Kern ───────────────────────────────────────────────
  {
    slug: "alterssicherungskommission",
    name: "Kommission für die langfristige Stabilisierung der Alterssicherung",
    kurzname: "Rentenkommission",
    ministerium: "BMAS",
    tier: 1,
    thema: "Soziale Sicherung",
    quelleUrl: "https://www.bmas.de/DE/Soziales/Rente-und-Altersvorsorge/Rentenreform-2025/Rentenkommission-2026/rentenkommission-2026.html",
    pollUrl: "https://www.bmas.de/DE/Soziales/Rente-und-Altersvorsorge/Rentenreform-2025/Rentenkommission-2026/rentenkommission-2026.html",
    cadence: "einmalig (Reformkommission)",
    nextExpected: "— (Bericht vorgelegt)",
    status: "bericht_vorgelegt",
    letzterBerichtUrl: "https://www.bundesregierung.de/resource/blob/975228/2444780/0fcbf810775351c64007ee6cb2c7cad9/2026-06-24-bericht-alterssicherungskommission-data.pdf?download=1",
    keywords: ["rentenkommission", "alterssicherungskommission", "rentenreform", "rentenpaket"],
    notiz: "Bericht dat. 2026-06-24, übergeben 23.06.2026 — Kommission faktisch abgeschlossen.",
  },
  {
    slug: "finanzkommission-gesundheit",
    name: "FinanzKommission Gesundheit",
    kurzname: "FKG",
    ministerium: "BMG",
    tier: 1,
    thema: "Gesundheit (GKV-Finanzierung)",
    quelleUrl: "https://www.bundesgesundheitsministerium.de/finanzkommission-gesundheit",
    pollUrl: "https://www.bundesgesundheitsministerium.de/finanzkommission-gesundheit",
    cadence: "laufend (mehrere Berichte)",
    nextExpected: "weiterer Bericht bis Ende 2026 (Strukturreformen)",
    status: "laufend",
    letzterBerichtUrl: "https://www.bundesgesundheitsministerium.de/fileadmin/Dateien/3_Downloads/F/FinanzKommission_Gesundheit/FinanzKommissionGesundheit_Erster_Bericht_20260330.pdf",
    keywords: ["finanzkommission gesundheit", "gkv-finanz", "krankenkassenbeitrag", "krankenkassenbeiträge", "alkoholsteuer", "zuckersteuer", "gesundheitssteuer"],
    notiz: "Alkohol-/Zuckersteuer-Empfehlungen (Nr. 64-66) stammen aus dem 1. Bericht — KEINE eigene 'Gesundheitssteuer-Kommission'.",
  },
  {
    slug: "pflegereform-pnog",
    name: "Pflegeneuordnungsgesetz / Empfehlungen Pflegepolitik",
    kurzname: "PNOG",
    ministerium: "BMG",
    tier: 1,
    thema: "Pflege",
    quelleUrl: "https://www.bundesgesundheitsministerium.de/finanzkommission-gesundheit",
    pollUrl: null,
    cadence: "einmalig (Gesetzgebung)",
    nextExpected: "Empfehlungen bis 01.10.2026; Umsetzung 01.01.2027",
    status: "laufend",
    letzterBerichtUrl: "https://www.bundesgesundheitsministerium.de/fileadmin/Dateien/3_Downloads/Gesetze_und_Verordnungen/GuV/P/RefE-Pflegeneuordnungsgesetz_PNOG.pdf",
    keywords: ["pflegereform", "pflegeneuordnung", "pnog", "pflegeversicherung", "pflegekommission", "pflegebeitrag"],
    notiz: "Referentenentwurf-/Gesetzgebungsprozess, keine Kommission mit eigener Pollseite — pollUrl=null, nur RefE-PDF als Seed.",
  },
  {
    slug: "expertenkommission-social-media",
    name: "Expertenkommission „Kinder- und Jugendschutz in der digitalen Welt“",
    kurzname: "Prien-Kommission",
    ministerium: "BMBFSFJ",
    tier: 1,
    thema: "Gesellschaft/Digitales",
    quelleUrl: "https://www.bmbfsfj.bund.de/bmbfsfj/themen/kinder-und-jugend/expertenkommission-kinder-und-jugendschutz-in-der-digitalen-welt",
    pollUrl: "https://www.bmbfsfj.bund.de/bmbfsfj/themen/kinder-und-jugend/kinder-und-jugendschutz/handlungsempfehlungen-der-expertenkommission-kinder-und-jugendschutz-in-der-digitalen-welt--290244",
    cadence: "gestufte Veröffentlichung (Bestandsaufnahme → Empfehlungen → Abschlussbericht)",
    nextExpected: "Abschlussbericht ausstehend (Empfehlungen 24.06.2026 vorgelegt)",
    status: "bericht_vorgelegt",
    letzterBerichtUrl: "https://www.bmbfsfj.bund.de/bmbfsfj/themen/kinder-und-jugend/kinder-und-jugendschutz/handlungsempfehlungen-der-expertenkommission-kinder-und-jugendschutz-in-der-digitalen-welt--290244",
    keywords: ["prien-kommission", "expertenkommission kinder", "jugendschutz", "kinder- und jugendschutz", "social media", "soziale medien", "altersgrenze für social", "handyverbot"],
    notiz: "56 Handlungsempfehlungen vorgelegt; letzter_bericht_url = Handlungsempfehlungen-Seite (Detailseite, kein direktes PDF).",
  },
  // ── TIER 2 — ständige Gremien / Daueranstalten ────────────────────────────
  {
    slug: "mindestlohnkommission",
    name: "Mindestlohnkommission",
    kurzname: null,
    ministerium: "unabhängig (BMAS-nah)",
    tier: 2,
    thema: "Arbeit",
    quelleUrl: "https://www.mindestlohn-kommission.de",
    pollUrl: "https://www.mindestlohn-kommission.de",
    cadence: "~2-jährl. Anpassungsbeschluss",
    nextExpected: "~Mitte 2027 (Beschluss für 2028/2029) (unbestätigt)",
    status: "laufend",
    letzterBerichtUrl: null,
    keywords: ["mindestlohnkommission", "mindestlohn"],
    notiz: "Beschlossen: 2026: 13,90 €, 2027: 14,60 €.",
  },
  {
    slug: "sachverstaendigenrat-wirtschaft",
    name: "Sachverständigenrat zur Begutachtung der gesamtwirtschaftlichen Entwicklung",
    kurzname: "Wirtschaftsweise",
    ministerium: "unabhängig",
    tier: 2,
    thema: "Wirtschaft",
    quelleUrl: "https://www.sachverstaendigenrat-wirtschaft.de",
    pollUrl: "https://www.sachverstaendigenrat-wirtschaft.de",
    cadence: "Jahresgutachten (Nov) + Sondergutachten",
    nextExpected: "Jahresgutachten ~Nov 2026 (unbestätigt)",
    status: "laufend",
    letzterBerichtUrl: null,
    keywords: ["wirtschaftsweise", "wirtschaftsweisen", "sachverständigenrat wirtschaft"],
    notiz: null,
  },
  {
    slug: "monopolkommission",
    name: "Monopolkommission",
    kurzname: null,
    ministerium: "unabhängig",
    tier: 2,
    thema: "Wettbewerb",
    quelleUrl: "https://www.monopolkommission.de",
    pollUrl: "https://www.monopolkommission.de",
    cadence: "Hauptgutachten (2-jährl.) + Sektorgutachten",
    nextExpected: "nächstes Hauptgutachten ~2026 (unbestätigt)",
    status: "laufend",
    letzterBerichtUrl: null,
    keywords: ["monopolkommission"],
    notiz: null,
  },
  {
    slug: "stabilitaetsrat",
    name: "Stabilitätsrat",
    kurzname: null,
    ministerium: "BMF/Länder",
    tier: 2,
    thema: "Öffentliche Finanzen",
    quelleUrl: "https://www.stabilitaetsrat.de",
    pollUrl: "https://www.stabilitaetsrat.de",
    cadence: "halbjährl. (Juni & Dez)",
    nextExpected: "~Dez 2026 (unbestätigt)",
    status: "laufend",
    letzterBerichtUrl: null,
    keywords: ["stabilitätsrat", "stabilitaetsrat"],
    notiz: null,
  },
  {
    slug: "sozialbeirat-rentenversicherungsbericht",
    name: "Sozialbeirat (Jahresgutachten zum Rentenversicherungsbericht)",
    kurzname: "Sozialbeirat",
    ministerium: "BMAS",
    tier: 2,
    thema: "Soziale Sicherung",
    quelleUrl: "https://sozialbeirat.de",
    pollUrl: "https://sozialbeirat.de/dokumente/",
    cadence: "jährl. (Nov, mit RV-Bericht)",
    nextExpected: "Jahresgutachten ~Nov 2026",
    status: "laufend",
    letzterBerichtUrl: "https://sozialbeirat.de/media/jahresgutachten_2025_end_m-u-barrierefrei_1.pdf",
    keywords: ["sozialbeirat", "rentenversicherungsbericht"],
    notiz: null,
  },
  {
    slug: "kef",
    name: "Kommission zur Ermittlung des Finanzbedarfs der Rundfunkanstalten",
    kurzname: "KEF",
    ministerium: "unabhängig (Länder)",
    tier: 2,
    thema: "Rundfunkbeitrag/Medien",
    quelleUrl: "https://www.kef-online.de",
    pollUrl: "https://www.kef-online.de",
    cadence: "~2-jährl. Bericht",
    nextExpected: "~2027 (25. Bericht) (unbestätigt)",
    status: "laufend",
    letzterBerichtUrl: null,
    keywords: ["rundfunkbeitrag", "kef-bericht", "finanzbedarf der rundfunk"],
    notiz: "24. Bericht Feb 2025.",
  },
  {
    slug: "svr-gesundheit",
    name: "Sachverständigenrat zur Begutachtung der Entwicklung im Gesundheitswesen",
    kurzname: "SVR Gesundheit",
    ministerium: "BMG",
    tier: 2,
    thema: "Gesundheit/Pflege",
    quelleUrl: "https://www.svr-gesundheit.de",
    pollUrl: "https://www.svr-gesundheit.de",
    cadence: "unregelmäßig (~12-Monats-Intervall)",
    nextExpected: "Gutachten „Qualität im Gesundheitswesen“ — Datum offen",
    status: "laufend",
    letzterBerichtUrl: "https://www.bundesgesundheitsministerium.de/ministerium/meldungen/uebergabe-svr-gutachten-22-05-25.html",
    keywords: ["svr gesundheit", "sachverständigenrat gesundheit", "gesundheitsweisen", "gutachten gesundheitswesen"],
    notiz: "Letztes Gutachten 22.05.2025.",
  },
  {
    slug: "svr-migration",
    name: "Sachverständigenrat für Integration und Migration",
    kurzname: "SVR Migration",
    ministerium: "unabhängig (Stiftungen)",
    tier: 2,
    thema: "Migration",
    quelleUrl: "https://www.svr-migration.de",
    pollUrl: "https://www.svr-migration.de",
    cadence: "jährl. Jahresgutachten",
    nextExpected: "Jahresgutachten ~2026 (unbestätigt)",
    status: "laufend",
    letzterBerichtUrl: null,
    keywords: ["svr migration", "sachverständigenrat für integration", "integration und migration", "migrationsgutachten"],
    notiz: null,
  },
  {
    slug: "expertenrat-klimafragen",
    name: "Expertenrat für Klimafragen",
    kurzname: "ERK",
    ministerium: "unabhängig (gesetzl., Klimaschutzgesetz)",
    tier: 2,
    thema: "Klima/Umwelt",
    quelleUrl: "https://expertenrat-klima.de/",
    pollUrl: "https://expertenrat-klima.de/publikationen/",
    cadence: "jährl. Prüfbericht (Frühjahr) + Stellungnahmen",
    nextExpected: "jährl. Prüfbericht ~Frühjahr 2027 (unbestätigt)",
    status: "laufend",
    letzterBerichtUrl: "https://expertenrat-klima.de/publikationen/pruefbericht-zur-berechnung-der-deutschen-treibhausgasemissionen-fuer-das-jahr-2025-und-zu-den-projektionsdaten-2026",
    keywords: ["expertenrat für klimafragen", "expertenrat klima", "co2-budget", "klimaziele 2030"],
    notiz: "Prüfbericht 18.05.2026: Zielverfehlung bis 2030 (60-100 Mt CO2 über Budget).",
  },
  {
    slug: "normenkontrollrat",
    name: "Nationaler Normenkontrollrat",
    kurzname: "NKR",
    ministerium: "Bundeskanzleramt (BMDS)",
    tier: 2,
    thema: "Bürokratie/Staatsmodernisierung",
    quelleUrl: "https://www.normenkontrollrat.bund.de",
    pollUrl: "https://www.normenkontrollrat.bund.de/Webs/NKR/DE/veroeffentlichungen/jahresberichte/jahresberichte_node.html",
    cadence: "jährl. Jahresbericht (Herbst)",
    nextExpected: "Jahresbericht ~Okt 2026 (unbestätigt)",
    status: "laufend",
    letzterBerichtUrl: "https://www.normenkontrollrat.bund.de/Webs/NKR/SharedDocs/Downloads/DE/Jahresberichte/2025-jahresbericht.pdf?__blob=publicationFile&v=5",
    keywords: ["normenkontrollrat", "bürokratiekosten", "erfüllungsaufwand"],
    notiz: "Jahresbericht 2025 (02.10.2025): Bürokratiekosten ~64 Mrd €/Jahr.",
  },
  {
    slug: "rat-nachhaltige-entwicklung",
    name: "Rat für Nachhaltige Entwicklung",
    kurzname: "RNE",
    ministerium: "unabhängig (berufen vom Bundeskanzler)",
    tier: 2,
    thema: "Nachhaltigkeit",
    quelleUrl: "https://www.nachhaltigkeitsrat.de",
    pollUrl: "https://www.nachhaltigkeitsrat.de/aktuelles/",
    cadence: "laufend (Empfehlungen/Stellungnahmen); alle 3 J. neu berufen",
    nextExpected: "laufende Empfehlungen (neu berufen 28.01.2026)",
    status: "laufend",
    letzterBerichtUrl: null,
    keywords: ["rat für nachhaltige entwicklung", "nachhaltigkeitsrat"],
    notiz: "Neu berufen 28.01.2026 (Vorsitz Gerald Haug).",
  },
  {
    slug: "deutscher-ethikrat",
    name: "Deutscher Ethikrat",
    kurzname: "Ethikrat",
    ministerium: "unabhängig (gesetzl., berät Bundestag + BReg)",
    tier: 2,
    thema: "Ethik/Medizin",
    quelleUrl: "https://www.ethikrat.org",
    pollUrl: "https://www.ethikrat.org/publikationen/stellungnahmen/",
    cadence: "Stellungnahmen unregelmäßig + Jahresbericht",
    nextExpected: "laufende Stellungnahmen",
    status: "laufend",
    letzterBerichtUrl: "https://www.ethikrat.org/publikationen/stellungnahmen/",
    keywords: ["ethikrat"],
    notiz: "Letzte Stellungnahme 11.06.2026.",
  },
  {
    slug: "svr-verbraucherfragen",
    name: "Sachverständigenrat für Verbraucherfragen",
    kurzname: "SVRV",
    ministerium: "BMJ (Verbraucherschutz)",
    tier: 2,
    thema: "Verbraucher",
    quelleUrl: "https://www.svr-verbraucherfragen.de",
    pollUrl: "https://www.svr-verbraucherfragen.de",
    cadence: "Gutachten unregelmäßig",
    nextExpected: "offen",
    status: "laufend",
    letzterBerichtUrl: null,
    keywords: ["sachverständigenrat für verbraucherfragen", "verbraucherfragen", "svrv"],
    notiz: "Seit Mai 2025 wieder beim BMJ (zuvor BMUV).",
  },
  {
    slug: "wiss-beirat-bmf",
    name: "Wissenschaftlicher Beirat beim Bundesministerium der Finanzen",
    kurzname: "Wiss. Beirat BMF",
    ministerium: "BMF",
    tier: 2,
    thema: "Finanzpolitik/Steuern",
    quelleUrl: "https://www.bundesfinanzministerium.de/Web/DE/Ministerium/Beiraete/Wissenschaftlicher_Beirat/wissenschaftlicher_beirat.html",
    pollUrl: "https://www.bundesfinanzministerium.de/Web/DE/Ministerium/Beiraete/Wissenschaftlicher_Beirat/Gutachten_und_Stellungnahmen/gutachten_und_stellungnahmen.html",
    cadence: "Gutachten unregelmäßig",
    nextExpected: "offen",
    status: "laufend",
    letzterBerichtUrl: null,
    keywords: ["wissenschaftlicher beirat beim bundesministerium der finanzen", "wissenschaftlicher beirat beim bmf", "beirat des bmf"],
    notiz: null,
  },
  {
    slug: "wiss-beirat-bmwe",
    name: "Wissenschaftlicher Beirat beim Bundesministerium für Wirtschaft und Energie",
    kurzname: "Wiss. Beirat BMWE",
    ministerium: "BMWE",
    tier: 2,
    thema: "Wirtschaftspolitik",
    quelleUrl: "https://www.bundeswirtschaftsministerium.de/Redaktion/DE/Textsammlungen/Ministerium/beiraete.html",
    pollUrl: "https://www.bundeswirtschaftsministerium.de/Redaktion/DE/Textsammlungen/Ministerium/beiraete.html",
    cadence: "Gutachten unregelmäßig",
    nextExpected: "offen",
    status: "laufend",
    letzterBerichtUrl: null,
    keywords: ["wissenschaftlicher beirat beim bundesministerium für wirtschaft", "wissenschaftlicher beirat beim bmwe", "beirat des bmwe"],
    notiz: null,
  },
];
